### PR TITLE
[FIX] count_inspections methods should be able to manage recordsets

### PR DESCRIPTION
**Pull request by SimoRubi**
Since they are called as compute methods, count_inspections methods should be able to manage recordsets

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking when CIs finish, as this is critical.

**Comment by pedrobaeza** [comment]
`quality_control_stock/models/qc_inspection.py:75:80: E501 line too long (80 > 79 characters)`

**Comment by SimoRubi** [comment]
@pedrobaeza now everything is green, should I fixup the fixuppable or not?

**Comment by pedrobaeza** [comment]
Not needed. I can squash on merge.

**Pull request merged**
