### PR TITLE
[14.0][MIG] stock_picking_product_kit_helper

### PR DESCRIPTION
**Pull request by clementmbr**
Standard migration to 14.0

### CODE REVIEW

**Comment by clementmbr** [comment]
FYI @kittiu
cc @rvalyi

**Review by rvalyi — APPROVED** [review]

**Comment by kittiu** [comment]
LGTM

**Review by kittiu — APPROVED** [review]

**Comment by clementmbr** [comment]
@kittiu do you think it can be merged ? Thanks!

**Pull request merged**
