### PR TITLE
[15.0] mrp_sale_info: Materialize link between sale order lines and created MOs

### PR DESCRIPTION
**Pull request by grindtildeath**
Improve test with 3 steps delivery route and use RecordCapturer

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by grindtildeath — COMMENTED** [review]
ping @pedrobaeza @tafaRU (as you're of the few contributors)

**Comment by pedrobaeza** [comment]
About the PR formal thing, please follow commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

About the feature itself, the module is for getting the sales info into the production. This seems bit to go in the opposite direction, isn't it?

**Comment by grindtildeath** [comment]
@pedrobaeza Thx I'll fix the commit message before merging.

If the goal of the module is only to provide sale information on the MO, and not MO information on the sale, we could still add the M2m field on mrp.production as well, but as it's wasn't a requirement, I did not add it...

IMO as long as the feature doesn't harm, I tend to prefer extending the scope of an existing module providing similar features than creating a dedicated module, which in turn would probably bring more confusion to end users in what each module provides.

**Comment by pedrobaeza** [comment]
OK, go ahead with the commit renaming.

**Pull request merged**
