### PR TITLE
[14.0][MIG] mrp_progress_button

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
Runbot error is related with another module:

https://github.com/OCA/manufacture/blob/14.0/quality_control_oca/models/qc_trigger_line.py#L30

**Comment by BernatPForgeFlow** [comment]
@Forgeflow

**Review by AaronHForgeFlow — APPROVED** [review]
functional tests :+1:  LGTM

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
