### PR TITLE
[14.0][FIX] bom_attribute_match: BOM unit of measure should match uom…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
… of a component_template_id.

### CODE REVIEW

**Comment by ilyasProgrammer** [comment]
@pedrobaeza I've added 'web' to oca_dependencies, but still having tests error regading web_domain_field. Could you help please ?

**Comment by pedrobaeza** [comment]
Dependencies are now handled by PIP: https://github.com/OCA/manufacture/blob/14.0/.copier-answers.yml#L5

so if the module has been merged today, you need to wait till tomorrow.

**Review by francesco-ooops — APPROVED** [review]
functional review ok 

@pedrobaeza can you clarify how to proceed?

**Comment by pedrobaeza** [comment]
I have re-launched tests to see

**Comment by francesco-ooops** [comment]
@pedrobaeza any idea on how to overcome license issue?

**Comment by pedrobaeza** [comment]
`mrp_bom_attribute_match` must be AGPL or to not depend on an AGPL module.

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers  merge?

**Review by francesco-ooops — CHANGES_REQUESTED** [review]
@ilyasProgrammer cannot choose another UoM in same category as component (product template) on BOM line, see video: https://recordit.co/zvF7yVXNCf

**Review by francesco-ooops — APPROVED** [review]
functional good now!

**Comment by francesco-ooops** [comment]
@pedrobaeza think this fix is good for merge?

**Comment by pedrobaeza** [comment]
I don't know this module, but I merge based on reviews:

/ocabot merge patch

**Pull request merged**
