### PR TITLE
[8.0][IMP] travis and README files

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can take also the occasion to add the runbot flag on the README

**Comment by tafaRU** [comment]
@pedrobaeza done

**Comment by lmignon** [comment]
:+1:

**Comment by tafaRU** [comment]
Code Climate image is broken, see https://github.com/tafaRU/manufacture/tree/8.0-travis-imp
How can I fix it?

**Comment by pedrobaeza** [comment]
Add the corresponding file: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.codeclimate.yml

**Comment by tafaRU** [comment]
@pedrobaeza where I have to add it? Could you please show me an example?
Thank you in advance.

**Comment by pedrobaeza** [comment]
You just need to simply add that file in the root folder of the repo

**Comment by tafaRU** [comment]
@pedrobaeza thanks, just added it but https://github.com/tafaRU/manufacture/tree/8.0-travis-imp is still broken.
I also noticed that in https://github.com/OCA/server-tools repo codclimate flag works although the corresponding file is missing.

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
It is needed to access code climate platform to add the repo, so I have made it.

About this, :+1:

**Comment by tafaRU** [comment]
@pedrobaeza 

> It is needed to access code climate platform to add the repo, so I have made it.

Ah ok, does it need an account with specific privileges or can I make it on my own?

[EDIT] Yes, I can make it on my own :wink: 

Last thing: is codeclimate.yml file useful or not?

Thank you in advance.

**Comment by pedrobaeza** [comment]
I think anybody can add an opensource GitHub repo, but I'm not sure.

The file serves for excluding of the analysis some files. If you don't do it, you won't get accurate results.

**Comment by tafaRU** [comment]
> I think anybody can add an opensource GitHub repo, but I'm not sure.

I tried to add https://codeclimate.com/github/OCA/l10n-italy ant it worked.

> The file serves for excluding of the analysis some files. If you don't do it, you won't get accurate results.

Ok,  thank you for your comprehensive answer!

**Pull request merged**
