### PR TITLE
[12.0][UPD] Update quality_control module logo

### PR DESCRIPTION
**Pull request by marcelsavegnago**
- Update quality_control module logo

### CODE REVIEW

**Comment by bodedra** [comment]
@marcelsavegnago Thanks for your contribution. We have already logo for quality_control module.  Ref: https://github.com/OCA/manufacture/blob/12.0/quality_control/static/description/icon.png

**Comment by pedrobaeza** [comment]
@bodedra It seems he is putting a higher resolution PNG (120x120 instead of 80x80). Why this change, @marcelsavegnago ?

**Comment by marcelsavegnago** [comment]
@pedrobaeza Because visually it is smaller than the icons of other modules. I use web responsive module and in this case i see the difference.

**Comment by pedrobaeza** [comment]
Maybe the problem is in `web_responsive` itself? cc @Yajo @Tardo

**Review by yajo — APPROVED** [review]
Not sure, but indeed Odoo 12 supplies icons of this size, so it seems a good patch to me anyways.

**Review by bodedra — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge minor

@Yajo please investigate the zoom question

**Pull request merged**
