### PR TITLE
[14.0] [MIG] mrp_warehouse_calendar

### PR DESCRIPTION
**Pull request by DavidBForgeFlow**
Standard migration to v14.

Depends on:
* [x] : https://github.com/OCA/stock-logistics-warehouse/pull/1043

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @sbidoul, we cannot understand [why travis is failling](https://travis-ci.com/github/OCA/manufacture/jobs/481809533#L469), everything seems fine from our side and we run pre-commit locally as well. Note that we have already created and merged some PR into branch 14.0 and everything worked fine. Thanks for you help!

**Comment by sbidoul** [comment]
Hi @LoisRForgeFlow The error is `No matching distribution found for odoo14-addon-stock_warehouse_calendar`. Could it be `stock_warehouse_calendar` is from another repo and not merged yet ? I've not much time to investigate right now. I can look deeper later today.

**Comment by sbidoul** [comment]
Yes I confirm that is the problem: stock_warehouse_calendar is not merged in 14.0.

**Comment by LoisRForgeFlow** [comment]
Oh, Ok I understand, so dependencies are being fetched via pip now, now it all makes sense. Thanks for the quick reply!

**Comment by LoisRForgeFlow** [comment]
@DavidBForgeFlow Usually if a module depends on an open PR, we add a comment in the description explicitly saying it. It helps to keep track of what is missing and what is linked to what.

I have added it now.

**Comment by sbidoul** [comment]
What you can do also is put `odoo14-addon-stock_warehouse_calendar @ git+https://github.com/OCA/stock-logistics-warehouse@refs/pull/1043/head#subdirectory=setup/stock_warehouse_calendar` in `test-requirements.txt` in this branch.

That's a mouthful :) but it is standard syntax (PEP 508 if you are curious) to tell pip where to get that dependency. It will make tests pass on runbot, as well as travis.

Dont forget to remove it before merging though.

**Comment by LoisRForgeFlow** [comment]
@sbidoul Thanks for the tip! In this specific case I think we can get the dependency merged soon, so we'll not do it, but it is certainly good for some other PR's depending on more complex modules.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by MateuGForgeFlow — APPROVED** [review]

**Pull request merged**
