### PR TITLE
[IMP] quality_control: decimal precision configurable

### PR DESCRIPTION
**Pull request by agaldona**

### CODE REVIEW

**Review by oihane — APPROVED** [review]
:+1: LGTM

**Comment by esthermm** [comment]
:+1:

**Review by LoisRForgeFlow — APPROVED** [review]
tested :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Change version number to reflect the update need

**Comment by agaldona** [comment]
Version changed.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
