### PR TITLE
[14.0][IMP] mrp_multi_level run in planning menu

### PR DESCRIPTION
**Pull request by andreampiovesana**
move to new planning menu

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
It's ok foo me

**Review by TheMule71 — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
It is fine to me, but please, move also the "MRP inventory" menu item.

Thanks

**Comment by LoisRForgeFlow** [comment]
@andreampiovesana now, can you squash both commits together? It will be ready to merge then.

**Comment by andreampiovesana** [comment]
I am not able
Ca you do it?

Il Mer 2 Giu 2021, 09:30 Lois Rilo ***@***.***> ha scritto:

**Comment by LoisRForgeFlow** [comment]
Done.

/ocabot merge minor

**Pull request merged**
