### PR TITLE
[ADD] Added quality_control_* modules

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**
Work in Progress

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @JayVora-SerpentCS 

What is the state of this migration?

**Comment by JayVora-SerpentCS** [comment]
Are you assigning to Darshan to do I assign to a team member? We actually missed it in the rush of projects and other modules! Apologies.

**Comment by LoisRForgeFlow** [comment]
No, just asking if you are going to continue this work. If not I can take it.

**Comment by pedrobaeza** [comment]
Superseeded by #198

**Pull request closed without merging**
