### PR TITLE
[REF] quality_control, quality_control_stock: update all fields once …

### PR DESCRIPTION
**Pull request by kos94ok-3D**
…per record

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why? Compute records are updated on cache, so no real improvement, and this has the contrary effect: you recompute everything each time you change any field.

**Comment by kos94ok-3D** [comment]
Records depend on object_id, what is a problem?
I add only required fields by object_id in function _get_values_by_object, so not all field will update.
Or I not see something?

**Comment by pedrobaeza** [comment]
But again, this is not a real improvement in performance not readability, so why change it?

**Comment by kos94ok-3D** [comment]
Variable, which depends on this object model, stick together I think it is more readability.
I agree that for the performance little impact.

**Comment by pedrobaeza** [comment]
I still see more readable the other way, with less indentation, each method for each field... so :-1: for this change, but others can give their opinion.

**Comment by kos94ok-3D** [comment]
Ok. Nobody interest in it, so I close PR.

**Pull request closed without merging**
