### PR TITLE
[15.0] [MIG] `mrp_bom_attribute_match`: Migration to 15.0

### PR DESCRIPTION
**Pull request by ivantodorovich**
**Easier to review commit by commit**
There are a number of fixes and improvements that are independent from the migration.
I rather leave them in separate commits to make it easier to backport them if needed.

I would've liked to drop the full `explode` overwrite, but I couldn't figure out how. Ideas welcome ^^

---

ping @ilyasProgrammer

### CODE REVIEW

**Review by ioans73 — APPROVED** [review]
LGTM 👍🏻

**Comment by francesco-ooops** [comment]
@ilyasProgrammer could you review?

**Review by ilyasProgrammer — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@pedrobaeza good for merge?

**Pull request merged**
