### PR TITLE
[12.0] porting mrp_production_auto_post_inventory

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by mrcast — COMMENTED** [review]
Functional test:
- partial production without work order OK, the partial quantity of finished product is posted in Stock
- partial production with work order NO:  the partial quantity of finished product is not posted in Stock and on production order there isn't the button "Post Inventory" as in v.11

**Comment by eLBati** [comment]
@mrcast `Post Inventory` is visible in debug mode (like in v11)

**Review by mrcast — APPROVED** [review]
Functional test: OK!
thanks

**Comment by eLBati** [comment]
@ageficent please have a look. Thanks

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
Thanks for the work!

/ocabot merge

**Comment by eLBati** [comment]
pedro

**Pull request merged**
