### PR TITLE
[FIX] mrp_operations_project - fix incorrect operator name in tasks

### PR DESCRIPTION
**Pull request by ddico**
A workcenter with multiple operators will trigger identical tasks for the same operation.

screen shot 2016-01-20 at 1 50 35 am

### CODE REVIEW

**Comment by anajuaristi** [comment]
Good point
If technically is rigth :+1 from my side

**Comment by pedrobaeza** [comment]
Totally right :+1: 

Merging.

**Comment by ddico** [comment]
That was fast :)

**Comment by JMODaERP** [comment]
Ddico Many thanks , that's what I was looking for !, because that operate 90 % of the companies in Spain . Thank you very much insist . Excellent, although this " merged " I also give you my approval. :+1: 
 Excellent.

**Pull request merged**
