### PR TITLE
[IMP] mrp_bom_hierarchy Remove field out of scope

### PR DESCRIPTION
**Pull request by quentinDupont**
- Remove `product_default_code` (named also `internal_reference` in compute method) which is not related to module scope
- Remove _order in mrp.bom which is not related to module scope

### CODE REVIEW

**Comment by quentinDupont** [comment]
ping @JordiBForgeFlow @MiquelRForgeFlow :-)

**Review by legalsylvain — APPROVED** [review]
make senses

**Comment by quentinDupont** [comment]
Rebased since https://github.com/OCA/manufacture/pull/1203 has been merged

**Review by LoisRForgeFlow — APPROVED** [review]
Fair enough, thanks!

**Pull request merged**
