### PR TITLE
[14.0[ADD] mrp_account_analytic: generate Analytic Items for manufacturing consumptions.

### PR DESCRIPTION
**Pull request by dreispt**
Extracted from the original proposed code for mrp_account_analytic_wip

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@dreispt It looks like there are some errors in travis, I'll review after those are resolved. Also in the PR description it's referencing a dependency but the manifest doesn't have that in the depends so maybe the PR description just needs updated?

**Comment by dreispt** [comment]
That is a good point. There were merges after last build, re-running it to see if there are changes.

**Comment by dreispt** [comment]
Re-build turned Travis green 😺

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
