### PR TITLE
[16.0][MIG] mrp_lot_number_propagation

### PR DESCRIPTION
**Pull request by bosd**
Standard migration using odoo-module-migrator.

### CODE REVIEW

**Comment by bosd** [comment]
@Dranyel-Bosd Can you please review?

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
@bosd can you squash the second commit (a fixup) into the first commit? It was a mistake when merging the 15.0 version.

**Comment by bosd** [comment]
Done!

**Comment by grindtildeath** [comment]
@bosd thanks for the mig. Can you please cherry pick https://github.com/OCA/manufacture/pull/1173 here ?

**Comment by bosd** [comment]
> Can you please cherry pick #1173 here ?

Thanks for this pointer, but I'm not sure what your asking. That pr is for a different module and cannot be cherry-picked here. This pr here already uses the changed vars from that commit.

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Review by grindtildeath — COMMENTED** [review]
@bosd My bad, I got confused between the two modules.

Can you still please bump development status to Beta?

**Review by grindtildeath — APPROVED** [review]

**Review by Dranyel-Bosd — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
