### PR TITLE
[15.0][MIG] mrp_bom_component_menu

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Adds a menu item *Bill of Material Components*.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
please rebase

**Comment by florenciafrigieri2** [comment]
@JuanyDForgeflow Hi! Is this ready to merge? Thanks.

**Review by florenciafrigieri2 — APPROVED** [review]
Functional Review LGTM

**Comment by JuanyDForgeflow** [comment]
@florenciafrigieri2 yes but I don't have permission to merge

**Comment by florenciafrigieri2** [comment]
@LoisRForgeFlow Hi Lois! Can you please merge this PR? Thanks!

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Pull request merged**
