### PR TITLE
[ADD] mrp_project

### PR DESCRIPTION
**Pull request by pedrobaeza**
# 
# MRP Project Link

This module links projects and tasks to _manufacturing orders_ (MO) and
_work orders_ (WO).
# Usage

In a manufacturing order (MO), you can select a project to be attached to it.
If none is selected, a project is automatically created when the MO is
confirmed.

When the MO starts, a task is created and assigned to the order.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@rafaelbn this one now depends on _mrp_analytic_ and it's ready for the review.

**Comment by rafaelbn** [comment]
Runbot fails

**Comment by pedrobaeza** [comment]
Yeah, I have added the new dependency. Please wait that I'm improving coverage.

**Comment by pedrobaeza** [comment]
OK, there it is! You have to let CIs finish, but now the coverage should be good enough.

**Comment by JMODaERP** [comment]
I have tested in runbot, OK, but the stages are not created:

I don´t select a project and then is automatically created when the MO is confirmed:

2015-12-04 16_40_18-manufacturing orders - odoo
I select a project to be attached to it:

2015-12-04 16_59_00-2015-12-04 16_42_16-manufacturing orders - odoo jpg - greenshot image editor

:+1:

**Comment by anajuaristi** [comment]
Same for me. Tested in runbot http://3136673-59-85b3ed.runbot1.odoo-community.org/web?db=3136673-59-85b3ed-all#menu_id=106&action=99

It creates correctly the project so :+1:

**Comment by JMODaERP** [comment]
Yes, I started the MO and a staged is created.

Thanks Peter, all is right.

**Comment by JavierIniesta** [comment]
Tested in runbot :+1:

**Comment by JMODaERP** [comment]
Task, no stage, excusme. I am thick.

**Comment by pedrobaeza** [comment]
For having stages you have to predefine them in the configuration, but this in unrelated to this PR.

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by pedrobaeza** [comment]
As there are enough positive reviews, I merge to continue with another PR of a module that depends on this one.

**Pull request merged**
