### PR TITLE
[14.0][FIX] mrp_sale_info remove duplicated button

### LINKED ISSUE #1107: Duplicated button 'Productions' in sale order
This code from `mrp_sale_info` module add a button to open manufacturing order generated from sale order:

https://github.com/OCA/manufacture/blob/bf31a8e90d099f73f2ad6a42fa3d1797e19d7a6b/mrp_sale_info/views/sale_order.xml#L1C1-L30C8

This is a similar button of the one created from the core `sale_mrp` module:

https://github.com/OCA/OCB/blob/26316dd56fa290b2a6d6366f325cdc9f4dcac0d6/addons/sale_mrp/views/sale_order_views.xml#L1C1-L18C16

### PR DESCRIPTION
**Pull request by sergiocorato**
closes: #1107

### CODE REVIEW

**Review by grindtildeath — APPROVED** [review]

**Review by grindtildeath — COMMENTED** [review]
Is the function `sale.order.action_view_production` still useful?

**Comment by sergiocorato** [comment]
> Is the function `sale.order.action_view_production` still useful?

Fixed, thanks!

**Review by rmorant — APPROVED** [review]
I found the same issue, and the PR fix it in my installation. Thank you.

**Pull request merged**
