### PR TITLE
[12.0][FIX] mrp_multi_level: Check BoM Line Attrs

### LINKED ISSUE #505: [12.0] mrp_multi_level: BoM explosion ignores product variant attributes
**Impacted versions:** 12.0, 13.0

**Steps to reproduce:** (using Customizable Desk from demo data)
1. Create configurable components products
   * Desk Leg, Steel
   * Desk Leg, Aluminum
   * Desk Leg, Custom
   * White Trim Kit
   * Black Trim Kit
1. Create BoM for product template "Customizable Desk"
   * Product = Desk Leg, Steel; Apply on Variants = Legs: Steel
   * Product = Desk Leg, Aluminum; Apply on Variants = Legs: Aluminum
   * Product = Desk Leg, Custom; Apply on Variants = Legs: Custom
   * Product = White Trim Kit; Apply on Variants = Color: White
   * Product = Black Trim Kit; Apply on Variants = Color: Black
1. Set supply route to Manufacture for Customizable Desk
1. Add product MRP Area Parameters for components listed above, and for Customizable Desk (Aluminum, Black)
1. Create sale order for product variant "Customizable Desk (Aluminum, Black)"
1. Run MRP Multi Level
1. Go to MRP Inventory list and look at the component products to procure

**Current behavior:**
The user is prompted to procure all component products

**Expected behavior:**
The user should only be prompted to procure components "Desk Leg, Aluminum", and "Black Trim Kit"

image

### PR DESCRIPTION
**Pull request by matt454357**
add a call to mrp.bom.line._skip_bom_line() method
fixes #505

### CODE REVIEW

**Comment by matt454357** [comment]
I added a test

**Review by LoisRForgeFlow — APPROVED** [review]
You are absolutely correct, I just tested locally and did the code review LGTM

Sorry for the delay on this and thanks for contributing!

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by LoisRForgeFlow** [comment]
@matt454357 would you mind forward porting this to v13?

**Comment by LoisRForgeFlow** [comment]
Forward ported here: https://github.com/OCA/manufacture/pull/530.

**Pull request merged**
