### PR TITLE
[12.0][MIG] account_move_line_manufacture_info

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

@Eficent

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@hveficent test are faililng, please could you have a look?

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review and functional test :+1:

**Comment by AdriaGForgeFlow** [comment]
> @hveficent test are faililng, please could you have a look?

Could you update review?

**Review by LoisRForgeFlow — APPROVED** [review]
LG

**Pull request merged**
