### PR TITLE
Migrated mrp_production_putaway_strategy to v13.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
CI is red, can you check?

**Comment by LoisRForgeFlow** [comment]
Can you rebase and squash your migration commits? That will fix runbot.

**Comment by LoisRForgeFlow** [comment]
I fixed the issues myself to allow this to move forward, hope you don't mind.

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, works good!

**Review by AdriaGForgeFlow — APPROVED** [review]
Tested locally :+1:

**Pull request merged**
