### PR TITLE
[13.0][REM] repair_calendar_view: remove this module (this resource was assimilated by the base_repair module)

### LINKED ISSUE #619: [RFC] Remove repair_calendar_view module from branch 12.0 and 13.0
Hello,

Recently, a module called base_repair was added to branch 12.0 and 13.0, which aims to be a module to maintain basic and common functionalities for an improvement of the repair module. In this module, the functionality of the repair_calendar_view module was incorporated to avoid conflicts with the types of views available for the repair module.

However, as already imagined, the coexistence of both modules affects the duplicity of some fields.
image

Do I do a PR to remove it from the repair_calendar_view module? Is it necessary to write a script to run after installing base_repair and uninstall repair_calendar_view if it is installed?

https://github.com/OCA/manufacture/pull/594
https://github.com/OCA/manufacture/pull/602
https://github.com/OCA/manufacture/pull/600

In branch 14.0 I suggest that the repair_calendar_view module is not migrated, but only the base_repair module
https://github.com/OCA/manufacture/pull/618

cc @rvalyi @dreispt

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This resource was assimilated by the base_repair module.

Ref. https://github.com/OCA/manufacture/issues/619

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by rvalyi — APPROVED** [review]

**Comment by rvalyi** [comment]
(the calendar view is here in base_repair already in v13 indeed https://github.com/OCA/manufacture/blob/13.0/base_repair/views/repair_order.xml )

**Comment by marcelsavegnago** [comment]
ping @sergiocorato

**Pull request merged**
