### PR TITLE
[IMP] mrp_production_real_cost: Load real cost from quant when product's cost method is real

### PR DESCRIPTION
**Pull request by agaldona**

### CODE REVIEW

**Review by Daniel-CA — APPROVED** [review]
:+1:

**Review by oihane — APPROVED** [review]
LGTM

**Comment by agaldona** [comment]
@pedrobaeza ¿Que te parece este cambio?

**Comment by pedrobaeza** [comment]
On OCA always in English, please. I'm not involved now with manufacturing and less with v8. Ana is PSC of this repo, so she can try and merge it.

**Comment by agaldona** [comment]
Ok. Thank you.

**Comment by anajuaristi** [comment]
+1 👍

**Review by andhit-r — APPROVED** [review]

**Pull request merged**
