### PR TITLE
[12.0][BACKPORT] mrp_planned_order_matrix

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Backport of #490 
CC @ForgeFlow @LoisRForgeFlow @JordiBForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Clicking on the menu item of this module does not open a new form window but uses current one:

image

**Comment by HviorForgeFlow** [comment]
Comments attended @LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
LG now thanks!

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: tested functionally

**Pull request merged**
