### PR TITLE
[14.0][ADD] mrp_package_propagation

### PR DESCRIPTION
**Pull request by sebalix**
Allow to propagate a package from a component to a finished product.

Similar to https://github.com/OCA/manufacture/tree/15.0/mrp_lot_number_propagation which was done for the lot/SN (on 15.0).

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
Can you please elaborate a bit the description to clarify the use case?

**Comment by simahawk** [comment]
@sebalix anything else to be done here beside squashing?

**Comment by sebalix** [comment]
@simahawk nothing else, working well on production for months now. PR rebased, ready to be merged.

**Review by simahawk — APPROVED** [review]

**Review by bosd — APPROVED** [review]
LGTM

**Pull request merged**
