### PR TITLE
[12.0][MIG/REN] mrp_repair_calendar_view -> repair_calendar_view

### PR DESCRIPTION
**Pull request by mariaasunciondaza**
@guadaltech

### CODE REVIEW

**Review by NachoAlesLopez — APPROVED** [review]
Code and functional review: OK.

**Comment by elvise** [comment]
Hi, any good news for merge...?
If I can help please let me know...

**Review by ps-tubtim — APPROVED** [review]
Functional Test: Ok. Code review: Ok.

**Comment by LoisRForgeFlow** [comment]
@mariaasunciondaza you didn't mention this is also a rename of the module...

Please, squash these commits together:
screenshot-2020-01-29


Thanks for the work.

**Comment by LoisRForgeFlow** [comment]
Thanks!

/ocabot merge

**Pull request merged**
