### PR TITLE
[14.0][IMP] mrp_subcontracting_resupply_link: add init hooks

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Functionally tested locally.

Ping @pedrobaeza

**Review by pedrobaeza — COMMENTED** [review]
With this method, are the FK and indexes for the m2m table created by the ORM?

**Comment by JordiMForgeFlow** [comment]
@pedrobaeza yes:

image

**Comment by MiquelRForgeFlow** [comment]
> are the FK and indexes for the m2m table created by the ORM?

This has been the case in Odoo for a long while, at least since v12.

**Pull request closed without merging**
