### PR TITLE
[10.0] [MIGR] mrp_calendar_view

### PR DESCRIPTION
**Pull request by tafaRU**
I took the occasion to rename the module to **mrp_repair_calendar_view**.
This PR replaces https://github.com/OCA/manufacture/pull/170.

### CODE REVIEW

**Review by eLBati — APPROVED** [review]

**Comment by eLBati** [comment]
@tafaRU please see https://github.com/tafaRU/manufacture/pull/1

**Comment by tafaRU** [comment]
@eLBati, just merged your PR, thanks!

**Comment by Daniel-CA** [comment]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]
Please squash your commits a bit

**Comment by tafaRU** [comment]
@pedrobaeza, done!

**Pull request merged**
