### PR TITLE
[14.0][FIX] repair_type: remove destination location for finished product

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
The destination location was removed from the repair since 12.0.

cc @ForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by JordiMForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Was it removed but not replaced by anything?

**Comment by JordiBForgeFlow** [comment]
@AaronHForgeFlow only in https://github.com/OCA/manufacture/blob/14.0/repair_refurbish/models/repair.py#L11

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
