### PR TITLE
[12.0][FIX] round icon

### PR DESCRIPTION
**Pull request by jarroyomorales**
Rounded a bit the module's icon to fit better in the `web_responsive` main menu.

image

image

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You can't remove the source SVG file. Modify that one instead with the round corners.

**Comment by jarroyomorales** [comment]
@pedrobaeza Okay! Where is it used?

**Comment by pedrobaeza** [comment]
It's used for:

- Generating the PNG from it.
- Be used as template for derivative modules that want to use this icon as base for adding a specific icon. Examples:

  https://github.com/OCA/vertical-association/blob/12.0/membership_extension/static/description/icon.svg
  https://github.com/OCA/vertical-association/blob/12.0/membership_initial_fee/static/description/icon.svg
  https://github.com/OCA/vertical-association/blob/12.0/membership_prorate/static/description/icon.svg
- Adapt on each version the style easily from an editable source.

**Comment by jarroyomorales** [comment]
@pedrobaeza Okay, I think it should be okay now

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
