### PR TITLE
[14.0][MIG] mrp_production_request

### PR DESCRIPTION
**Pull request by ypapouin**
This PR is an alternative to #625, I'm not against the refactoring proposal but I don't have time to refactor all modules that depends on this one at the moment. The refactoring could be done in a second PR.

- I've added more tests to ensure that the migration does not break the existing workflow.
- The list view has been updated to the 14.0 design
- A basic kanban view has been added.

image
image

### CODE REVIEW

**Comment by elvise** [comment]
Hi @ypapouin thanks for this PR!
I tested it but looks doesn't work "trigger manufacture request" please check this [video](http://recordit.co/nRLySqalX6)

**Comment by ypapouin** [comment]
@elvise, you are right. The problem happens when the `mrp_sale_info` module is installed.
It shows up that the current implementation was invalid (by removing fields from a static list).
An exception is raised when running the scheduler (but silenced because the scheduler run in parallel).

Its working now, but please note that since MTO rule is not enabled, you have to create a « minimum stock rule » and the product must have a BoM (even empty). (This restriction could be removed in another PR since a BoM is no more necessary for a production order)

**Comment by elvise** [comment]
@ypapouin thanks for your work! 
i’m testing your PR and why not add an action in rule ?

IMG_1274

for complex operations it will be more scalable…

**Comment by ypapouin** [comment]
@elvise, replacing the boolean option with a route should be possible but I would prefer having this module migrated first.

**Pull request closed without merging**
