### PR TITLE
[14.0][MIG] quality_control_oca

### PR DESCRIPTION
**Pull request by enriquemartin**
standard migration + 
- "refactor" of ir.model.acess.csv: shorten up the names, fill missing groups and add wizard rule
- added trigger menu on quality control/configuration
- fix web_icon path

### CODE REVIEW

**Review by jcdrubay — APPROVED** [review]
Tested: this base module is working as I would expect.

**Comment by anajuaristi** [comment]
:-1: 
It's not rigth. I wouldn't merge. The basis of the module is triggering quality control inspections on picking or manufacturing documents.
in this PR the "trigger" many2one on products is going against a new objetct and it doesnt' allow to select any picking type so functionally is totally broken.
I would propose to migrate the module AS IS without including any functional "inprovement". 
Thank you

**Comment by pedrobaeza** [comment]
@anajuaristi without `quality_control_stock_oca` or `quality_control_mrp_oca`, such processes won't be available. The base module only allows manual inspections.

**Comment by enriquemartin** [comment]
@anajuaristi the changes I understand you are referring to were already implemented in the [v13 version](https://github.com/OCA/manufacture/blob/35e8103c57b794cf7f83660a79a369b319495eb3/quality_control_oca/models/product_template.py#L14), so I do not think this is the place to discuss them. This PR is just a simple migration and cleanup, as established in the first comment. Thanks!

**Comment by anajuaristi** [comment]
Hi @pedrobaeza @enriquemartin 
Sorry, we didn't use this modules in V13 but only in V12, so I was expecting same behavior. So, we see that there is not a PR about quality_control_stock_oca and quality_control_mrp_oca to be migrated from V13 to V14
If noone is working on that we can asume the task. But, please let us know.
Thank you:
Ana

**Comment by enriquemartin** [comment]
Hi @anajuaristi 
We already have migrated this addons, but we would need this PR to be merged to propose those new PRs.
Thanks!

**Review by anajuaristi — APPROVED** [review]

**Review by Daniel-CA — APPROVED** [review]
LGTM :+1:

**Comment by anajuaristi** [comment]
@enriquemartin It has been merged. 
You can propose the new PR's. We will be ready to review if you need it.

Thank you:
Ana

**Pull request merged**
