### PR TITLE
[8.0][ADD] mrp_production_manual_close

### PR DESCRIPTION
**Pull request by Daniel-CA**
This module modifies mrp production workflow to finish the production orders manually adding a new close button.

### CODE REVIEW

**Comment by Daniel-CA** [comment]
@pedrobaeza Looks like that the test in mrp_production_real_cost is giving an error because this module changes the behavior when the production is done but not all the products to be produced has been produced.
I am having 2 errors, one with the amount of analytic lines created that doesn't match (remaining movements are cancelled) and the other one is with the amount when the `operation_time_line` start_time changes and the amount doesn't change.
Shoud I change the test on mrp_production_real_costs or I need to do a glue module?

**Comment by pedrobaeza** [comment]
You have to inhibit this behavior when testing if a context key is not provided. Ask @oihane that has made something similar.

**Comment by oihane** [comment]
Here it is an example
https://github.com/odoomrp/odoomrp-wip/blob/8.0/product_variants_no_automatic_creation/models/product_template.py#L56

**Comment by Daniel-CA** [comment]
I tried to avoid behavior adding a condition in the workflow but I have an empty frozendict on context so I can't add the key to differentiate code execution.

**Comment by andhit-r** [comment]
Hi @pedrobaeza @oihane @Daniel-CA , i tried to solve travis problem by using @oihane example. I could not see that example can be used for this PR. No behavior in mrp_production_manual_close that needed to be inhibit. Would you kindly give pointer which behavior that need to be inhibited?

Meanwhile i have tested to:

1. change test on mrp_production_real_cost (https://github.com/andhit-r/manufacture/tree/8.0-fix-issue-147). I only made sure that assert on analytic line happen when production state is done (see https://github.com/andhit-r/manufacture/blob/8.0-fix-issue-147/mrp_production_real_cost/tests/test_mrp_production_real_cost.py#L43, https://github.com/andhit-r/manufacture/blob/8.0-fix-issue-147/mrp_production_real_cost/tests/test_mrp_production_real_cost.py#L74, and https://github.com/andhit-r/manufacture/blob/8.0-fix-issue-147/mrp_production_real_cost/tests/test_mrp_production_real_cost.py#L90), and
2. Migrate **mrp_production_manual cost**

It passed all travis checks.

Then i tried to alter the test without mirgating mrp_production_manual_cost. It passed travis checks and same coverage score (OCA/8.0 https://coveralls.io/github/OCA/manufacture?branch=8.0 against https://coveralls.io/github/andhit-r/manufacture?branch=8.0-real-cost-alter-test).

Is it possible that we just go ahead with altering test on mrp_production_real_cost?

**Pull request closed without merging**
