### PR TITLE
[17.0][MIG] mrp_production_note: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 158474
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/manufacture/issues/1125

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM, code review and tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM, code review and tested in runboat

**Pull request merged**
