### PR TITLE
[10.0] MIG mrp repair discount

### PR DESCRIPTION
**Pull request by hurrinico**
Migrate module to v10 and add discount to fees lines

### CODE REVIEW

**Review by eLBati — CHANGES_REQUESTED** [review]
Please check tests

**Comment by hurrinico** [comment]
@eLBati fixed

**Comment by eLBati** [comment]
@hurrinico it seems there are too many commits (some are duplicated?)

**Comment by hurrinico** [comment]
i close this in favor of https://github.com/OCA/manufacture/pull/222

**Pull request closed without merging**
