### PR TITLE
[17.0][MIG] mrp_tag: Migration to 17.0

### PR DESCRIPTION
**Pull request by aarribas-alquemy**

### CODE REVIEW

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboat.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Can you check field positioning?

In previous versions, the tags were placed just before the status.

image

Could you adjust that?

**Comment by peluko00** [comment]
Any update @aarribas-alquemy?

**Review by peluko00 — APPROVED** [review]
LGTM when migration commits rebase into one, tested in runboat and code review

**Comment by peluko00** [comment]
@LoisRForgeFlow seems it's ready to merge when rebase the migration commits into one

**Comment by peluko00** [comment]
@aarribas-alquemy can you rebase the 2 migration commits into one. Thanks!

**Review by mpascuall — APPROVED** [review]
Once the migration commits are rebased into one, LGTM tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM tested in runboat, but please, squash commits.

**Comment by aarribas-alquemy** [comment]
Commits rebased into one.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
