### PR TITLE
[TMP][DO NOT MERGE] Test for seeing CI state

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@LoisRForgeFlow there's a failing test in `mrp_multi_level`. Can you please check?

**Comment by LoisRForgeFlow** [comment]
I think it might be the same thing reported here https://github.com/OCA/manufacture/issues/1307. It is probably a timing issue, I suspect there is a range of time in which that tests fails. In my local currently is fine, I restarted the CI here to see if it gets green now.

**Comment by pedrobaeza** [comment]
I don't think so. I have just opened the PR (so not around midnight), and it's consistent failing in all the attempts.

**Comment by LoisRForgeFlow** [comment]
I'm checking in local with freeze_time and I am not succeeding making that test fail. It can also be an interference with another module. Checking.

**Comment by LoisRForgeFlow** [comment]
An update, the conflict is with mrp_production_date_planned_finished, I will check in more details when I have time later.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Today tests passed, which I suspected. So the issue is only happening on Mondays. I will try to get care of it during this week and propose a fix for next Monday. In the meanwhile your other PR should be no longer blocked.

**Comment by pedrobaeza** [comment]
Wow, it's the first time I see that tests are blocked depending on the week day. It would be good to have that fixed. Launching the merge on the other PRs.

**Pull request closed without merging**
