### PR TITLE
[15.0][ADD] purchase_mrp_distribution: New module to distribute qty of move in diferent products

### PR DESCRIPTION
**Pull request by CarlosRoca13**
This module aims to address the need to receive a generic product, but until the moment of reception, we do not know the quantity that we might receive of its specific products.

Using kits was not suitable for us, because to account for a unit of the kit product, the quantity specified in the BoM must be received. Therefore, we opted to define a new type of BoM called distribution.

In this way, upon receiving a unit of any product added to the BoM, it will be accounted for as a unit of the generic product and will be reflected in the svls as separate products, but they will be accounted for in the purchase line as part of the product.

cc @Tecnativa TT49937

ping @pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]
Code and functional review OK.

**Comment by bosd** [comment]
@CarlosRoca13 Can you please rebase to recreate a runboat?

**Comment by CarlosRoca13** [comment]
@bosd done!

**Review by bosd — APPROVED** [review]
Fucntional test. LGTM

**Comment by CarlosRoca13** [comment]
ping @pedrobaeza

**Comment by bosd** [comment]
Oops, I missed the filling test. 
Can you look into it?

**Comment by pedrobaeza** [comment]
It's not our fault... https://github.com/OCA/manufacture/pull/1388

**Pull request merged**
