### PR TITLE
[14.0][ADD] mrp_helper: Add methods shared between various mrp modules

### PR DESCRIPTION
**Pull request by mt-software-de**
This PR is adding a new module called mrp_helper to share some useful methods between various mrp modules.
In fact now it only adds the possibility to ignore the _bom_find method of mrp.bom.

### CODE REVIEW

**Comment by mt-software-de** [comment]
Maybe @jaredkipe you want also review this one?

**Comment by mt-software-de** [comment]
@grindtildeath, @LoisRForgeFlow could review this one, whats your opinion about this?

**Comment by grindtildeath** [comment]
@mt-software-de Thanks for the contribution.

I would suggest to call the module something like `mrp_bom_find_ignore` to reflect what it's actually doing and set a development status to alpha.

**Comment by mt-software-de** [comment]
@OCA/manufacturing-maintainers can anyone please reopen this PR?

**Comment by LoisRForgeFlow** [comment]
@mt-software-de it cannot be reopened because the "branch was force-pushed or recreated".

**Pull request closed without merging**
