### PR TITLE
[9.0] mrp_bom_dismantling: remove dependency

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Little change to remove the dependency in stock_available_mrp of mrp_bom_dismantling as response to discussion in https://github.com/OCA/manufacture/issues/189

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
I pushed another commit changing the method name to avoid problems in databases with both modules installed `mrp_bom_dismantling` and `stock_available_mrp`. Not sure whether this is the best option.

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
In my local the testd are running fine, but travis tests are failing [here](https://github.com/OCA/manufacture/blob/10.0/mrp_bom_dismantling/tests/test_template.py#L20). I checked another PR in the repository and they are failling also there, however I cannot find the reason, it seems a simple test:
1. Create a product.template
2. Create a BOM related
3. Check the bom_count expecting it to have changed from 0 to 1.

The compute method for bom_count is overrited in this module. But neither the original method (`_bom_orders_count`) or the new compute method (`_bom_count`) are inherited nor modified in any other module in  this repository.

**Comment by JordiBForgeFlow** [comment]
@cyrilgdn Do you agree?

**Comment by serpentcs-dev1** [comment]
@lreficent I checked in my local the [computation method](https://github.com/OCA/manufacture/blob/10.0/mrp_bom_dismantling/models/product_template.py#L15) is triggered when the template is created but not when the bom for that is created so, maybe you have to call it manually before asserting the value.
`tmpl1._bom_count()`

**Comment by LoisRForgeFlow** [comment]
@darshan-serpent yeah, let's give it a try!

**Comment by LoisRForgeFlow** [comment]
@darshan-serpent Fixed now, can you give your review here please?

**Review by OSevangelist — APPROVED** [review]
Changes seem reasonable to me

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please change version number

**Review by serpentcs-dev1 — APPROVED** [review]
Code Review LGTM :+1:

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza version bumped

**Comment by LoisRForgeFlow** [comment]
ping @pedrobaeza your review is blocking, could you check?

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
