### PR TITLE
[12.0][IMP] base_repair: repair order graph view and menu reporting

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @rvalyi @eduaparicio @dreispt

**Review by rvalyi — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @renatonlima

**Review by dreispt — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@OCA/manufacturing-maintainers Can you merge this PR?

**Comment by marcelsavegnago** [comment]
@OCA/manufacturing-maintainers can we merge this PR ?

**Pull request merged**
