### PR TITLE
[14.0][MIG + IMP]repair_discount

### PR DESCRIPTION
**Pull request by manuelregidor**
IMP: discount column in repair order PDF

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by manuelregidor** [comment]
@LoisRForgeFlow Could you review, please? Thank you.

**Review by HaraldPanten — APPROVED** [review]

**Comment by ValentinVinagre** [comment]
@LoisRForgeFlow Tested in production with client and everything is working properly.

**Comment by HaraldPanten** [comment]
@pedrobaeza @gurneyalex @LoisRForgeFlow Could you have a quick look at that, please?

THX

**Pull request merged**
