### PR TITLE
[17.0][MIG] account_move_line_mrp_info

### PR DESCRIPTION
**Pull request by CarlosVForgeFlow**
Migration to 17.0

@ForgeFlow

### CODE REVIEW

**Comment by MateuGForgeFlow** [comment]
Hi @CarlosVForgeFlow,

Can you please reopen this PR and remove the "depends on". The stock-logistics-workflow PR has been superseeded by https://github.com/OCA/stock-logistics-warehouse/pull/2160

Thank you!

**Comment by MiquelRForgeFlow** [comment]
@MateuGForgeFlow closed PRs by github-actions can only be opened by people who has merge powers in the repository, like @LoisRForgeFlow

**Comment by CarlosVForgeFlow** [comment]
Dependency removed! @MateuGForgeFlow

**Review by JordiMForgeFlow — APPROVED** [review]
code + functional 👍🏼

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
