### PR TITLE
[9.0][ADD] mrp_bom_location

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
MRP BOM Location
================

This module adds the location field to the Bill of Materials and its
components. This may be useful to distinguish between different BoMs for the
same product or to highlight the preferred locations to fetch the
components from.

### CODE REVIEW

**Review by gurneyalex — DISMISSED** [review]
hello, this looks nice. Can you fix the tiny flake8 issues. 

Also I just changed the travis config file which should allow ppl to test the PR on runbot (currenly the pdf reports are failing). Can you rebase the PR?

**Comment by LoisRForgeFlow** [comment]
@gurneyalex Done, thanks!

**Comment by guewen** [comment]
The lint still complains about a few issues

**Comment by LoisRForgeFlow** [comment]
@guewen @gurneyalex This is :green_apple: now!

**Review by yvaucher — APPROVED** [review]
Green and LGTM. ready to be merged !

**Pull request merged**
