### PR TITLE
[15.0] Create module mrp_workorder_lock_planning

### PR DESCRIPTION
**Pull request by grindtildeath**
This module allows to lock the planning of workorders to avoid
any unintended rescheduling.

A Lock/Unlock button will be displayed once a workorder is planned.

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]
looking at the code, seems good

**Review by i-vyshnevska — APPROVED** [review]

**Comment by grindtildeath** [comment]
@OCA/manufacturing-maintainers CAn we get this merged as it's "Alpha"?

**Pull request merged**
