### PR TITLE
[17.0][MIG] quality_control_oca: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 155125

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/manufacture/issues/1125

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Works good, checked in runboat

**Review by lbarry-apsl — APPROVED** [review]
Works, tested on Runboat

**Pull request merged**
