### PR TITLE
[13.0][IMP] quality_control_oca: add chatter to quality tests

### PR DESCRIPTION
**Pull request by cubells**
Forward https://github.com/OCA/manufacture/pull/784

### CODE REVIEW

**Comment by cubells** [comment]
@pedrobaeza I don't know whats the matter here.

**Comment by pedrobaeza** [comment]
There was a problem with CI definition. Now it should be OK with the changes I have made on the repo:

/ocabot merge minor

**Comment by pedrobaeza** [comment]
@sbidoul there's still one error updating POT files asking about git user:

https://github.com/OCA/manufacture/runs/6124381586?check_suite_focus=true

Can you please help?

**Comment by sbidoul** [comment]
That's a strange error. Have you seen it elsewhere ? Is the 13.0 branch using the standard GitHub action from the template ?

**Comment by pedrobaeza** [comment]
No, this is the first time. I have just converted the repo to GH actions using latest template:

https://github.com/OCA/manufacture/commit/436de99ae79f83485eada9356cd1b808252d530a

**Comment by sbidoul** [comment]
Weird, maybe it's a transient. @cubells could you rebase ?

**Comment by cubells** [comment]
@sbidoul done!

**Comment by pedrobaeza** [comment]
@cubells can you please fw-port it to v14 and v15 as well?

Thanks.

**Pull request merged**
