### PR TITLE
[12.0][NEW] Repair Payment Term

### PR DESCRIPTION
**Pull request by mileo**
- Add a field payment_term_id on repair orders;
- Onchange from res.partner sale payment_term_id;
- Copy it to the invoice.

cc: @gabrielcardoso21 @marcelsavegnago

### CODE REVIEW

**Comment by mileo** [comment]
Not related but, repair payment mode: https://github.com/OCA/bank-payment/pull/789

**Comment by gabrielcardoso21** [comment]
@mileo this field shoud also go to the report of the repair quotation.

**Comment by mileo** [comment]
> @mileo this field shoud also go to the report of the repair quotation.

Done

**Review by marcelsavegnago — APPROVED** [review]
LGTM. Tested on the Runbot

**Review by gabrielcardoso21 — APPROVED** [review]
We can't forget to create translations for the report terms later.

**Comment by mileo** [comment]
@dreispt i think that the merge command fail.

/ocabot merge nobump

**Comment by dreispt** [comment]
Hmm, I think the maintainer's key does not work for new modules.

**Pull request merged**
