### PR TITLE
[14.0] mrp_bom_attribute_match: backport updates from v15 

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
picked:
https://github.com/OCA/manufacture/pull/888
https://github.com/OCA/manufacture/pull/958
https://github.com/OCA/manufacture/pull/983

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ivantodorovich can you take another look? Thank you :)

**Comment by ivantodorovich** [comment]
Now it's looking better, indeed!
Only one thing missing: some of the commits have a message like this:

```
# Conflicts:
#	mrp_bom_attribute_match/models/product.py
```

That makes no sense for the history, we need to keep only the original message here

**Comment by ilyasProgrammer** [comment]
updated

**Review by ivantodorovich — APPROVED** [review]
Excellent! 
Thanks a lot !

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers good for merge?

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza go?

**Pull request merged**
