### PR TITLE
[14.0][UPD] mrp_bom_attribute_match: backport updates from V15. + mrp…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…_account_bom_attribute_match module.

mrp_bom_attribute_match - updates from V15
mrp_account_bom_attribute_match - new module from V15

p.s.
cherry-pick wont work here.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ivantodorovich what do you think of this cumulative backporting?

**Comment by ivantodorovich** [comment]
I think it makes sense to backport these. When doing so, though, please keep the original commit message.
"backport" makes sense for a PR title/description, but it would make little sense in the commit history

**Comment by francesco-ooops** [comment]
@ilyasProgrammer also please add changes from https://github.com/OCA/manufacture/pull/983

**Comment by francesco-ooops** [comment]
@ivantodorovich do you have documentation to share on how to do a backporting?

**Comment by ivantodorovich** [comment]
I don't know of any docs at hand, unfortunately.

> p.s.
> cherry-pick wont work here.

why is that? 🤔 normally that's how I'd do it

**Comment by ilyasProgrammer** [comment]
another try here
https://github.com/OCA/manufacture/pull/986

**Pull request closed without merging**
