### PR TITLE
[15.0][FIX] mrp_progress_button: Fix unstart functionality

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Fix Unstart button functionality, position and visibility.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Changes in the qty_producing field will change the status so this makes more sense :+1:

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by AaronHForgeFlow** [comment]
Ping @LoisRForgeFlow

**Review by JoanMForgeFlow — APPROVED** [review]
Makes sense, code review OK!
@LoisRForgeFlow  WDYT

**Review by JoanMForgeFlow — COMMENTED** [review]
@simahawk can we merge this please?
Thanks in advance!

**Pull request merged**
