### PR TITLE
[14.0][ADD] mrp_bom_attribute_match

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Using this module you can have dynamic components of a BOM. Component is generated based on match of attributes and values of production product and component.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

@OCA/manufacturing-maintainers we consider this a very convenient module for manufacturing products with hundreds of color variants, we really look forward to your opinion 🎯

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers let me know whether the description is all clear

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers can you take a look? thanks!

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers weekly request for review :)

**Comment by francesco-ooops** [comment]
@anajuaristi @LoisRForgeFlow @pedrobaeza any chance to review? thank you

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers could you please take a look?

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers can I please receive at least a reply?

**Comment by elvise** [comment]
@pedrobaeza can you check also this one? 🙂

**Comment by francesco-ooops** [comment]
> /ocabot merge nobump

Thank you!!!

**Pull request merged**
