### PR TITLE
[14.0][ADD] mrp_component_operation_scrap_reason

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
This module allows to pass a reason to scrap with MRP component operation (glue module).

Depends on #917 

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow can you rebase this one?

**Comment by DavidJForgeFlow** [comment]
> @DavidJForgeFlow can you rebase this one?

Done!

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
