### PR TITLE
[14.0][ADD] mrp_production_back_to_draft

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
This module allows to return to draft a confirmed or cancelled MO.

@ForgeFlow

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM functional and code review 👍🏿

**Review by LoisRForgeFlow — COMMENTED** [review]
Have you considered 2 step manufacturing? in which upon confirmation a picking for the components is created.

**Comment by DavidJForgeFlow** [comment]
> Have you considered 2 step manufacturing? in which upon confirmation a picking for the components is created.

Yes, as we need to cancel first the stock.moves to be able to mark them as draft, the cancellation method handles multi-step MO.

**Comment by LoisRForgeFlow** [comment]
> > Have you considered 2 step manufacturing? in which upon confirmation a picking for the components is created.
> 
> Yes, as we need to cancel first the stock.moves to be able to mark them as draft, the cancellation method handles multi-step MO.

Thanks! can you adjust the new module name in the commit msg and PR title?

**Comment by DavidJForgeFlow** [comment]
Done!

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
