### PR TITLE
[FIX] when a bom has quantity multiplier, consider it

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
When the BOM is specified with a certain quantity, then consider it as a factor during the BOM explosion.

image

cc @LoisRForgeFlow @HviorForgeFlow @AdriaGForgeFlow

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
This is equivalent to https://github.com/odoo/odoo/blob/13.0/addons/mrp/models/mrp_production.py#L599

**Comment by LoisRForgeFlow** [comment]
Just applied pre-commit.

**Review by AdriaGForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, looks good :+1:

**Pull request merged**
