### PR TITLE
[12.0][MIG] Migrated mrp_auto_assign to v12.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**
Please review and give feedback.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by gdgellatly — CHANGES_REQUESTED** [review]
@sudhir-erpharbor Please update to the modular readme format as at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Otherwise LGTM.

**Comment by sudhir-erpharbor** [comment]
@gdgellatly Thanks for your feedback. Sure will do it soon.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by alan196 — APPROVED** [review]
Code review LGTM

**Review by Nikul-Chaudhary — APPROVED** [review]
Code Review LGTM :+1:

**Review by gdgellatly — APPROVED** [review]

**Review by gdgellatly — CHANGES_REQUESTED** [review]
Sorry, I thought the readme was done - change back to request changes

**Comment by sudhir-erpharbor** [comment]
Done. Please review.

**Comment by LoisRForgeFlow** [comment]
Can you squash your last 2 commits into one single migration one? This is ready.

**Review by ThijsvOers — APPROVED** [review]
I have tested this module in the odoo 12 test environment with several scenario's and I approve the pull request

**Review by ThijsvOers — APPROVED** [review]

**Pull request merged**
