### PR TITLE
[14.0][MIG] mrp_bom_line_sequence : Migration to 14.0  

### PR DESCRIPTION
**Pull request by mymage**

### CODE REVIEW

**Comment by mymage** [comment]
Please review @marcelofrare @andreampiovesana @primes2h

**Review by marcelofrare — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
go

**Comment by andreampiovesana** [comment]
merge?

**Review by andreampiovesana — APPROVED** [review]
merge

**Comment by andreampiovesana** [comment]
why do you not merge?

**Comment by mymage** [comment]
@OCA/manufacturing-maintainers please merge this PR or suggest improvements, thanks

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
