### PR TITLE
[14.0][MIG] mrp_auto_assign

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM, but it's sad no version 13.0 was done :(

**Review by CarlosVForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks for the migration note :+1: 

/ocabot merge nobump

**Pull request merged**
