### PR TITLE
[12.0][ADD] mrp_subcontracting: Backport from odoo v13

### PR DESCRIPTION
**Pull request by pedrobaeza**
This module is a backport of the one found in official Odoo 13.0, adapted
for this version.

For the configuration and usage, see Odoo documentation:

https://www.odoo.com/documentation/user/13.0/manufacturing/management/subcontracting.html

cc @Tecnativa TT18586

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`product_quick_bom` is failing. I will check how tests are performed in it, if it's a problem already in 12.0 branch, or incompatibility between both.

**Comment by pedrobaeza** [comment]
I have patched the other module fail in https://github.com/OCA/manufacture/commit/940725b9d394b0950f1a51f28763b81423a73db2, so it's ready to be reviewed.

cc @rvalyi

**Comment by tonygalmiche** [comment]
Hi @pedrobaeza,
I followed the documentation:
https://www.odoo.com/documentation/user/13.0/fr/manufacturing/management/subcontracting.html

I got this error when I received it : 
image

**Comment by pedrobaeza** [comment]
Please put the steps to reproduce the error.

**Comment by tonygalmiche** [comment]
I installed on my computer these modules : Manufacturing, Sale, Purchase and mrp_subcontracting

I created this product : 
image

I created this bom : 
image


I created this order : 
image

I tried to make the picking
image

**Comment by pedrobaeza** [comment]
Can you please try to reproduce it on runbot, not on your local?

**Comment by tonygalmiche** [comment]
Same problem : 
image

here is my test base:
http://3421579-501-f32ce8.runbot2.odoo-community.org

**Comment by rvalyi** [comment]
cc @clementmbr

**Comment by pedrobaeza** [comment]
The problem was all your raw materials were consumable. I have reconfigured it and it's working in this PO: http://3421579-501-f32ce8.runbot2.odoo-community.org/web?#id=9&action=366&model=purchase.order&view_type=form&menu_id=206, with this picking: http://3421579-501-f32ce8.runbot2.odoo-community.org/web?#id=31&action=178&active_id=9&model=stock.picking&view_type=form&menu_id=206 and this MO: http://3421579-501-f32ce8.runbot2.odoo-community.org/web?debug=1#id=10&action=328&model=mrp.production&view_type=form&menu_id=176

**Comment by tonygalmiche** [comment]
Hi @pedrobaeza,
Indeed it works now with runbot. Thank you for your answer.
But I still can't get this module to work on my computer
I always have the same message
Yet all of my product can be stored now (Product Type = Storable Product)
However I tried to put the exact same configuration as on runbot
Thank you in advance

**Comment by pedrobaeza** [comment]
I can't say, sorry. You can activate tracking for seeing the "Record components" button on the incoming picking so that you can track possible problems.

**Review by Tardo — APPROVED** [review]
:+1: LGTM

**Comment by pedrobaeza** [comment]
@rvalyi is OK to merge this?

**Review by HaraldPanten — APPROVED** [review]
Seems to be OK

**Comment by Daniel-CA** [comment]
LGTM

**Review by Daniel-CA — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it as it counts with enough approvals and no more feedback from Akretion:

/ocabot merge nobump

**Pull request merged**
