### PR TITLE
[MIG] mrp_bom_component_menu: Migration to 12.0

### PR DESCRIPTION
**Pull request by skukered**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@skukered  Thanks for your contribution, have a look at the comparison acroos versions:

v11:
image

v12:
image

You can see that it is not correctly migrated, the tree and search views are missing in the process. Please can you fix this?

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Because of my previous comment

**Comment by skukered** [comment]
ok

**Comment by LoisRForgeFlow** [comment]
@skukered still missing the sarch view, to be able to search by parent and component.

**Comment by skukered** [comment]
That view was removed in version 12, I add it

**Comment by LoisRForgeFlow** [comment]
Yes, I know, they removed it because it was not used, that's why this module was needed.

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by LoisRForgeFlow** [comment]
Please, squash your last 3 commits into one.

**Review by tbaden — COMMENTED** [review]
if you like some aesthetic changes in the xml file
following contribution guidline https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#id23 , but optional for approvement.

will approve, when commits are squashed 👍

**Comment by skukered** [comment]
I'm checking how to do it.

**Review by tbaden — APPROVED** [review]
thanks for the squash

**Pull request merged**
