### PR TITLE
[12.0][FIX] base_repair: FIX __manifest__.py - summary

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by bodedra — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by HaraldPanten — APPROVED** [review]

**Review by sergiocorato — APPROVED** [review]

**Pull request merged**
