### PR TITLE
[ADD] mrp_mto_with_stock_lite module

### PR DESCRIPTION
**Pull request by kos94ok-3D**
Introduce my idea from an issue: #451

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
@sergiocorato what do you think?

**Comment by sergiocorato** [comment]
@kos94ok-3D I tested it, it seems to work :+1: This replace #411 and #412 
Can you format code to OCA standard and adapt test from #411 ?
To @OCA/manufacturing-maintainers : can this module replace all work on mrp_mto_with_stock? or someone is interested in forecasting feature?

**Comment by kos94ok-3D** [comment]
@sergiocorato Have I create keep new module or can migrate mrp_mto_with_stock?

**Comment by sergiocorato** [comment]
For this kind of evaluation need some PSC member, perhaps @LoisRForgeFlow can help?

**Comment by kos94ok-3D** [comment]
Hi, @LoisRForgeFlow. Could you review it?

**Comment by desdelinux** [comment]
@LoisRForgeFlow @pedrobaeza @avanzosc Could you review it?

**Pull request closed without merging**
