### PR TITLE
[12.0][ADD] mrp_production_filter_lot

### PR DESCRIPTION
**Pull request by SirTakobi**
Superseding https://github.com/OCA/manufacture/pull/730

### CODE REVIEW

**Comment by SirTakobi** [comment]
> Hey @SirTakobi, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla Here is a list of the users:
> 
> * @SirTakobi (login unknown in OCA database)
> 
> Appreciation of efforts, OCA CLAbot

Sent

**Comment by SirTakobi** [comment]
@OCA/manufacturing-maintainers can someone have a look? Thanks!

**Review by eLBati — APPROVED** [review]
Thanks

**Comment by SirTakobi** [comment]
@OCA/manufacturing-maintainers can someone have a look? Thanks!

**Comment by SirTakobi** [comment]
@OCA/manufacturing-maintainers can someone have a look? Thanks!

**Review by mrcast — APPROVED** [review]
Functional test ok!

**Pull request merged**
