### PR TITLE
[IMP] mrp_bom_attribute_match: BOM line form : show component_templat…

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
…e_id

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

@ivantodorovich good for you?

**Review by ivantodorovich — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@ivantodorovich can you merge too? :)

**Comment by ivantodorovich** [comment]
Oh, I forgot I have maintainer merge powers on this module :D 
sure thing!

/ocabot merge minor

**Pull request merged**
