### PR TITLE
[17.0][MIG] mrp_workorder_sequence: Migration to 17.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 154409
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/manufacture/issues/1125

### CODE REVIEW

**Review by lbarry-apsl — APPROVED** [review]
Validated functionality in Runboat

**Review by mpascuall — APPROVED** [review]
Functionally working, tested in runboat

**Comment by peluko00** [comment]
Ready for merge @LoisRForgeFlow ?

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

/ocabot merge nobump

**Pull request merged**
