### PR TITLE
[ADD] repair_picking_after_done : Transfer repaired move to another location directly from repair order

### PR DESCRIPTION
**Pull request by DhavalTforgeFlow**
This module adds the functionality to create transfer of repaired move once repair order is done.

@ForgeFlow

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@DavidBForgeFlow can you review?

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@DhavalTforgeFlow Can you add a test script?

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by DavidJForgeFlow — APPROVED** [review]

**Pull request merged**
