### PR TITLE
[12.0][MIG] mrp_warehouse_calendar

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check runbot and Travis status

**Comment by Saran440** [comment]
This module depend on stock_warehouser_calendar but module is not merge. What should I do?

**Comment by LoisRForgeFlow** [comment]
@Saran440 You should reference here the PR of your dependency.

**Comment by Saran440** [comment]
This module depends of stock_warehouse_calendar

[OCA/stock-logistics-warehouse #564](https://github.com/OCA/stock-logistics-warehouse/pull/564)

**Comment by LoisRForgeFlow** [comment]
@Saran440 Dependency is merged.

**Comment by Saran440** [comment]
I try to push force again. but this not found 'stock_warehouse_calendar ' module. How can i do that?

**Comment by tbaden** [comment]
@Saran440 did you rebase from the upstream (oca repository)?

**Comment by Saran440** [comment]
@tbaden no. i rebase at my repo.
My remote origin is git@github.com:Saran440/manufacture.git

**Comment by LoisRForgeFlow** [comment]
@Saran440 I added the oca_dependencies that were missing and tried to fix the author of your migration commit (it was set to the OCA bot).

**Comment by LoisRForgeFlow** [comment]
@Saran440 

> Saran saranp502@homtail.com (no github login found)

Is this your email for github? Have you signed the CLA?

**Comment by LoisRForgeFlow** [comment]
Nevermind, I was misstyping hotmail, now it is fixed. Let's wait travis and runbot.

**Review by LoisRForgeFlow — COMMENTED** [review]
travis :green_apple: 

LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by Saran440** [comment]
@lreficent Thanks a lot for your help :)
I thought I have to recommit .

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
