### PR TITLE
[15.0][MIG] mrp_sale_info: Migration to `15.0`

### PR DESCRIPTION
**Pull request by Mantux11**
Supersed of #795 

Standard migration to 15.

### CODE REVIEW

**Comment by Mantux11** [comment]
@HviorForgeFlow, @ajaniszewska-dev Could you review this PR? I improved tests, changed to correct version, and corrected quotes. Thanks.

**Review by HviorForgeFlow — APPROVED** [review]
code review :+1:

**Review by gaikaz — APPROVED** [review]

**Comment by gaikaz** [comment]
@OCA/manufacturing-maintainers 
Could we get a maintainer review please 🙏🏻

**Comment by Mantux11** [comment]
@OCA/manufacturing-maintainers Could this PR get some attention, and maybe could be merged?

**Review by LoisRForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
