### PR TITLE
[17.0][MIG] mrp_planned_order_matrix

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:
- https://github.com/OCA/web/pull/2756

### CODE REVIEW

**Comment by MateuGForgeFlow** [comment]
Hi @JasminSForgeFlow.
Dependency has been merged!

**Review by LoisRForgeFlow — APPROVED** [review]
Functional review :+1:

**Comment by LoisRForgeFlow** [comment]
It is a straight forward migration, it was closed by the bot because it did not have much attention... I'll merge to avoid that it get closed again:

/ocabot merge nobump

**Pull request merged**
