### PR TITLE
[8.0] ADD  mrp_production_traceability

### PR DESCRIPTION
**Pull request by eLBati**
From https://github.com/odoomrp/odoomrp-wip/tree/8.0/mrp_production_traceability

### CODE REVIEW

**Comment by eLBati** [comment]
@pedrobaeza do you know a valid github email for Ainara and alfredo?

**Comment by anajuaristi** [comment]
Hi @eLBati 
Their names are @agaldona and @alfredo_avanzosc

**Comment by eLBati** [comment]
Thanks @anajuaristi I would need valid email addresses, because in the not recognized commits
```<ainara@ainara-Presario-CQ57.(none)>```
and
```<alfredo@alfredo-Aspire-5738.(none)>```
was used

cc @agaldona @alfredoavanzosc

**Comment by agaldona** [comment]
Hello my valid email is <ainaragaldona@avanzosc.es> and the @alfredoavanzosc email is <alfredodelafuente@avanzosc.es>
You can contact me if you need anything else.

**Comment by eLBati** [comment]
@agaldona thanks, done

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
I tried to merge as it was green, but seems that after rebasing it is not. I will close as this is stale, please reopen and fix it if you think it is still relevant.

**Pull request closed without merging**
