### PR TITLE
[14.0][MIG] base repair

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by marcelsavegnago** [comment]
ping @mileo

**Comment by marcelsavegnago** [comment]
ping @rvalyi @dreispt

**Comment by marcelsavegnago** [comment]
ping @mileo @rvalyi @dreispt

**Comment by marcelsavegnago** [comment]
ping @bodedra @HaraldPanten

**Comment by Reyes4711-S73** [comment]
Functional review @marcelsavegnago. If you can, could you add spannish translations? I did it before, so you must only download the file and put in your module.
[es.zip](https://github.com/OCA/manufacture/files/6180305/es.zip)

**Review by mileo — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
> Functional review @marcelsavegnago. If you can, could you add spannish translations? I did it before, so you must only download the file and put in your module.
> [es.zip](https://github.com/OCA/manufacture/files/6180305/es.zip)

@Reyes4711 Translations must be done via Weblate when the module is merged it will be possible to translate. If you agree, approve the PR please.

https://odoo-community.org/page/translate

**Review by Reyes4711-S73 — APPROVED** [review]

**Pull request merged**
