### PR TITLE
[16.0][ADD] mrp_bom_select_product_variant

### PR DESCRIPTION
**Pull request by quentinDupont**
New module for v16 that favors Product variant selection for BOM creation
When selecting a product variant, the linked product template is automatically selected.

Tree and filter view are also changed : you see and search with product variant.

mrp_bom_select_product_variant

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks ! code review / no test.

**Comment by legalsylvain** [comment]
@OCA/manufacturing-maintainers could you take a look here ?

**Review by rvalyi — APPROVED** [review]
LGTM

**Pull request merged**
