### PR TITLE
[IMP] quality_control: approving inspections only quality control managers

### PR DESCRIPTION
**Pull request by agaldona**

### CODE REVIEW

**Comment by agaldona** [comment]
@odoomrp/developers  Can you take a review please?

**Review by oihane — APPROVED** [review]
LGTM :+1:

**Comment by Daniel-CA** [comment]
:+1:

**Comment by esthermm** [comment]
:+1:

**Comment by agaldona** [comment]
cc @pedrobaeza @tafaRU @sbidoul @gurneyalex

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please change version number and I'll merge it.

**Comment by agaldona** [comment]
Version number changed.

**Pull request merged**
