### PR TITLE
[IMP] mrp_operations_extension: WO finish, do not consume with the remaining raw materials

### PR DESCRIPTION
**Pull request by Daniel-CA**
- New behaviour added when finishing WO and there are pending movements

all info:
https://github.com/odoomrp/odoomrp-wip/pull/966

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add tests.

**Comment by Daniel-CA** [comment]
Can someone check this? The coverage/coveralls is 100%

**Comment by agaldona** [comment]
:+1:

**Comment by Daniel-CA** [comment]
Updated tittle of the PR to clarify what is the reason for this:
When an operation is finished, it should not produce with the remaining raw materials.

**Comment by anajuaristi** [comment]
It's not correctly explained yet. Produce is produce and consume is
consume. You don't produce with remaining row materials. It's wrong aproach.
It would be better something like ... to finish one operation all materials
have to be consumed or cancelled.

**Comment by Daniel-CA** [comment]
Right, in operations you consume, I just misspelled, changed.

**Comment by pedrobaeza** [comment]
OK, seems to be good enough :+1:

**Comment by anajuaristi** [comment]
do not consume remaining raw materials serís entonces más correcto

**Comment by oihane** [comment]
:+1: LGTM

**Comment by anajuaristi** [comment]
@oihane @Daniel-CA @pedrobaeza 

We need this merged and it has got 3 :+1:  LGTM + mine so... I will merge in short time if there is no problem.

**Pull request merged**
