### PR TITLE
[14.0][MIG] mrp_bom_line_sequence

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Migration to 14.0

Provide a new field sequence on bom components, which allows to manage the
order of moves in a picking.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional + code

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
merge?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge?

**Comment by LoisRForgeFlow** [comment]
@JuanyDForgeflow can you have a look, pre-commit is complaning https://github.com/OCA/manufacture/runs/7181003770?check_suite_focus=true. Maybe you need a rebase and run pre-commit again.

**Comment by JuanyDForgeflow** [comment]
@LoisRForgeFlow it's fixed now

**Comment by dreispt** [comment]
There are merge conflicts to be solved.

**Comment by JuanyDForgeflow** [comment]
@dreispt looks like this is already on branch 14.0
https://github.com/OCA/manufacture/tree/14.0/mrp_bom_line_sequence

I'm closing this one

**Pull request closed without merging**
