### PR TITLE
[MIG] quality_control: Migration to 12.0

### PR DESCRIPTION
**Pull request by NachoAlesLopez**
cc @guadaltech

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Some runbot warnings:
```
2019-05-10 09:26:50,132 164 WARNING openerp_test odoo.models: The model qc.inspection.set.test has no _description
2019-05-10 09:26:53,896 164 WARNING openerp_test odoo.addons.base.models.ir_ui_view: The group product.group_uom defined in view qc.inspection.form does not exist!
2019-05-10 09:26:54,000 164 WARNING openerp_test odoo.addons.base.models.ir_ui_view: The group product.group_uom defined in view qc.inspection.line.tree does not exist!
```

**Comment by NachoAlesLopez** [comment]
> Some runbot warnings:
> 
> ```
> 2019-05-10 09:26:50,132 164 WARNING openerp_test odoo.models: The model qc.inspection.set.test has no _description
> 2019-05-10 09:26:53,896 164 WARNING openerp_test odoo.addons.base.models.ir_ui_view: The group product.group_uom defined in view qc.inspection.form does not exist!
> 2019-05-10 09:26:54,000 164 WARNING openerp_test odoo.addons.base.models.ir_ui_view: The group product.group_uom defined in view qc.inspection.line.tree does not exist!
> ```

Should be fixed now. Thanks for the heads-up.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM :+1:

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
