### PR TITLE
[10.0][IMP] make icon compatible with the app drawer

### PR DESCRIPTION
**Pull request by pedrocs-exo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, for proper integration, you should leave the icon in one color (convert main figure to only white).

**Comment by pedrocs-exo** [comment]
Agree, just didn't want to upset the original designer.  New commit available.

**Comment by pedrobaeza** [comment]
It was me, so no offense :smiley: 

I'll still remove the color in inner parts. If you want, I can do it for not bothering you more.

**Comment by pedrocs-exo** [comment]
Please, be my guest! I trust you'll handle it better than me. Saludo

**Comment by pedrobaeza** [comment]
@pedrocasi as you have used the standard 10.0 branch, when I have pushed the branch, the PR got automatically closed. I have opened #338 with the new icon. Please tell me what do you think about it.

**Comment by pedrocs-exo** [comment]
Perfect!

**Pull request closed without merging**
