### PR TITLE
[14][MIG] mig mrp_bom_component_menu

### PR DESCRIPTION
**Pull request by florian-dacosta**
FYI @LoisRForgeFlow @JordiBForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
Missing Apply on Variant field in tree view, otherwise LGTM :+1:

**Review by kos94ok-3D — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Comment by AaronHForgeFlow** [comment]
@OCA/manufacturing-maintainers this is ready :)

**Review by bodedra — APPROVED** [review]
👍

**Review by andreampiovesana — APPROVED** [review]
merge?

**Pull request merged**
