### PR TITLE
[13.0][ADD] mrp_workorder_update_component

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Allows to modify component lines in work orders.

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow avoid plurals in module names, mrp_workorder_update_component should be fine.

**Comment by DavidJForgeFlow** [comment]
> @DavidJForgeFlow avoid plurals in module names, mrp_workorder_update_component should be fine.

Changed!

**Comment by DavidJForgeFlow** [comment]
@LoisRForgeFlow tests added!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
