### PR TITLE
[15.0][MIG] mrp_bom_line_sequence

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Edit: well, actually it works, because the sequence is not propagated to any other place in Odoo. Actually the description of the module is misleading because the sequence is not propagated anywhere, but standard Odoo will take the same order when creating an MO for the BOM. The refactor is not needed in this case.

**Review by AaronHForgeFlow — COMMENTED** [review]
Fuctional tests ok!

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by JasminSForgeFlow — APPROVED** [review]
Functional Test

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
