### PR TITLE
[13.0][MIG] mrp_multi_level

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration.

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Travis error being discussed here: https://github.com/OCA/maintainer-quality-tools/issues/623.

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional test and code review :+1:

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Pull request merged**
