### PR TITLE
[13.0] [MIG] mrp_production_request: Migrated module in v13.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
You should apply black changes and migration in 2 different commits to ease review. Also the there are unmitigated dependencies, have you migrated them? can you propose them to the respective repositories and point to the migration pull request here?

Thanks for contributing!

**Comment by LoisRForgeFlow** [comment]
> You should apply black changes and migration in 2 different commits to ease review. Also the there are unmitigated dependencies, have you migrated them? can you propose them to the respective repositories and point to the migration pull request here?
Thanks for contributing!

Can you just take the time (as you are also asking for mine to review) to answer my comments... they are unattended.

**Review by dreispt — CHANGES_REQUESTED** [review]
@chandresh Please resolve comment https://github.com/OCA/manufacture/pull/437#issuecomment-563213499

**Comment by Chandresh-SerpentCS** [comment]
PR Replaced by #495

**Comment by Chandresh-SerpentCS** [comment]
> You should apply black changes and migration in 2 different commits to ease review. Also the there are unmitigated dependencies, have you migrated them? can you propose them to the respective repositories and point to the migration pull request here?
> 
> Thanks for contributing!

I did separate commits (black-changes & migration changes) in #495

**Comment by bodedra** [comment]
@Chandresh-SerpentCS You may close this PR.

**Pull request closed without merging**
