### PR TITLE
10.0 mig quality control stock

### PR DESCRIPTION
**Pull request by SimoRubi**
Migration of quality_control_stock.
Plus a minor fix to control_quality module.

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]

**Comment by eLBati** [comment]
- Move 6b31dd54342e94996c856471ae5330caa278b511 to another PR
 - squash commits from the same author
 - About 78bcee6663991be787bfbbc342eaef9216bb1380 ask @agaldona for the correct email address

**Comment by SimoRubi** [comment]
- moved https://github.com/OCA/manufacture/commit/6b31dd54342e94996c856471ae5330caa278b511 to https://github.com/OCA/manufacture/pull/287

**Comment by SimoRubi** [comment]
- squashed commits from common authors

**Comment by SimoRubi** [comment]
@agaldona which email should I set on your commit? That has to correspond with the email set in your GitHub account, thanks

**Comment by agaldona** [comment]
@SimoRubi I no longer work with Odoo for few months. All commits I made for Odoo features where related to ainaragaldona@avanzosc.es, but I had to change the related mail in my account. Now, I use ainara.galdona@gmail.com. In any case, use the one you prefer. Thanks.

**Comment by SimoRubi** [comment]
@eLBati everything done

**Review by eLBati — APPROVED** [review]

**Review by hurrinico — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/manufacturing-maintainers can this be merged?
Thanks

**Comment by SimoRubi** [comment]
@OCA/manufacturing-maintainers can this be merged?
So I can go on with #283.
Thanks

**Pull request merged**
