### PR TITLE
[8.0][FIX] quality_control: not take into account inactivated tests trigger lines

### PR DESCRIPTION
**Pull request by agaldona**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This shouldn't be needed, as inactive records (with `active=False`) are automatically discarded by ORM...

**Comment by agaldona** [comment]
Bat there is no active field in trigger lines, it is in the test, and you are filtering trigger lines. We have received an issue about it.

**Review by pedrobaeza — APPROVED** [review]
OK, I see.

**Comment by agaldona** [comment]
Other option would be creating an active field related to the test's active field in trigger lines. And it would be filtered by orm.

**Comment by pedrobaeza** [comment]
OK, seems correct this way.

**Review by andhit-r — APPROVED** [review]

**Review by oihane — APPROVED** [review]
LGTM

**Comment by agaldona** [comment]
@pedrobaeza Can we merge this PR?

**Pull request merged**
