### PR TITLE
[13.0][IMP]mrp_multi_level, specific group to run mrp manually

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Froward port #492

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Let's resolve this in v12 first, then come back to this one.

**Comment by LoisRForgeFlow** [comment]
@AaronHForgeFlow Can you update this one with the changes suggested in v12? and also can you cherry-pick this commit: https://github.com/OCA/manufacture/commit/24b9b15b50bc00657066db505e9b444598cdc375 ?

Thank you!

**Comment by AaronHForgeFlow** [comment]
Nice feature! thanks

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, :+1:

**Pull request merged**
