### PR TITLE
[8.0] [ADD] mrp_operations_time_control

### PR DESCRIPTION
**Pull request by pedrobaeza**
# 
# Manufacturing Operations - Time control

This module allows to control the duration of the manufacturing
operations (work orders) through the interface controls.
# Configuration

Go to _Settings > Manufacturing_ and activate "Manage routings and work orders"
for handling the features of this module.
# Usage

On _Manufacturing > Manufacturing > Manufacturing Orders_ or
_Manufacturing > Manufacturing > Work Orders_, you can see the existing work
orders. In each of them, there are buttons for starting, pausing or stopping
them. Pressing these buttons, there are records that are automatically created
or modified in the tab "Machine up time" for tracking the time spent.

You can also maintain this table by hand going to
_Manufacturing > Manufacturing > Operation Time Lines_.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This PR includes the commits from https://github.com/OCA/manufacture/pull/57
============================================================================
To allow to try it runbot, but shouldn't be analysed all code nor merged. Only commit from 7 of december are the relevant ones.

**Comment by pedrobaeza** [comment]
cc @rafaelbn, @JavierIniesta, @JMODaERP

**Comment by JavierIniesta** [comment]
Tested in runbot :+1:

**Comment by rafaelbn** [comment]
Tested in local enviroment :+1:  (as runbot is very slowly today)

**Comment by anajuaristi** [comment]
Yes. It gave me 504 Gateway Time-out, just now.

**Comment by pedrobaeza** [comment]
Rebased also and waiting for final review for merging.

**Comment by rafaelbn** [comment]
@pedrobaeza it's impossible to test it in runbot, do you need again test in local?

**Comment by JMODaERP** [comment]
OK. I tested, but i should like that in "Extra information": End Date in PLanned Date = Scheduled Date + Number of hours: :+1: 

Some like this:

2015-12-09 17_03_24-devel - work orders - odoo

**Comment by JavierIniesta** [comment]
:+1:

**Comment by rafaelbn** [comment]
We should review https://github.com/OCA/manufacture/pull/61#issuecomment-163308955

**Comment by pedrobaeza** [comment]
This in unrelated to this PR, and even with mrp_operations_extension. It's more an Odoo bug, because that are standard fields.

**Comment by rafaelbn** [comment]
OK, thanks @pedrobaeza . :+1:

**Comment by pedrobaeza** [comment]
Merging also this one, and continuing with the rest of the PRs. We are close to finish this main block...

**Pull request merged**
