### PR TITLE
[16][MIG] mrp_bom_component_menu

### PR DESCRIPTION
**Pull request by florian-dacosta**
Standard Migration

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review

**Comment by florian-dacosta** [comment]
@CasVissers-360ERP @JuanyDForgeflow

A small review please ?

**Comment by CasVissers-360ERP** [comment]
Runboat build is still pending waiting for that.

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by anajuaristi — APPROVED** [review]

**Pull request merged**
