### PR TITLE
[14.0] mrp_bom_attribute_match: backport from v15 updates + mrp_account_bom_attribute_match

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
replacement for https://github.com/OCA/manufacture/pull/977

picked:
https://github.com/OCA/manufacture/pull/888
https://github.com/OCA/manufacture/pull/958
https://github.com/OCA/manufacture/pull/983

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
@ilyasProgrammer great!

@ivantodorovich good for you?

**Comment by francesco-ooops** [comment]
@ivantodorovich if you could approve this it would make merge much easier :) thanks!

**Comment by ivantodorovich** [comment]
The `[MIG] mrp_bom_attribute_match: Migration to 15.0 ` commit shouldn't be here, we don't want it in `14.0` branch
In consecuence, the `[14.0][UPD] updates after cherry pick` commit shouldn't be created either.

What we shuold have, instead, is the other commits adapted (if needed) to `14.0`.

**Comment by ilyasProgrammer** [comment]
It will be 100 times more labor intensive

**Pull request closed without merging**
