### PR TITLE
[IMP] mrp_bom_hierarchy: Open form view of child BoM when there is only 1 child BoM

### PR DESCRIPTION
**Pull request by FranzPoize**

### CODE REVIEW

**Review by quentinDupont — APPROVED** [review]
Exactly what i wanted to code when discovering this module !
LGTM, tested on clean v16

**Review by legalsylvain — APPROVED** [review]
thanks a lot.
code review / no test.

**Comment by FranzPoize** [comment]
Who should i ping to get this merged ?

**Comment by legalsylvain** [comment]
> Who should i ping to get this merged ?

Maintainers are available in this repo : 

https://github.com/OCA/repo-maintainer-conf/blob/master/conf/psc/manufacturing.yml

**Comment by FranzPoize** [comment]
Hi @gurneyalex , @LoisRForgeFlow , @grindtildeath , @pedrobaeza, Is it possible to merge this ? Thanks in advance !

**Comment by LoisRForgeFlow** [comment]
@FranzPoize A bit nitpicking but could you follow the commit [message standards](https://www.odoo.com/documentation/12.0/developer/reference/guidelines.html#commit-message-structure)? [TAG] module_name: short summary. E.g: in this case you could write: "[IMP] mrp_bom_hierarchy: Open form view of child BoM when there is only 1 child BoM" (you almost got it right in the PR title, but ADD tag is to add new modules)

**Comment by FranzPoize** [comment]
Thanks for the help. The commit message has been changed

**Pull request merged**
