### PR TITLE
[14.0][MIG] mrp_production_note: Migration to 14.0

### PR DESCRIPTION
**Pull request by janikvonrotz**
Standard migration from 13.0 to 14.0.

### CODE REVIEW

**Comment by janikvonrotz** [comment]
I need some help on squashing. Can somebody guide me on how to squash the commits from 
19b549b to 1288b62 ?

**Comment by janikvonrotz** [comment]
I have created a non-OCA module here: https://www.odoo-wiki.org/mrp-production-note.html

**Review by ivantodorovich — APPROVED** [review]

**Comment by lbelorgey** [comment]
> I need some help on squashing. Can somebody guide me on how to squash the commits from [19b549b](https://github.com/OCA/manufacture/commit/19b549ba455f3bd85ba4981674abbdd7c17feb35) to [1288b62](https://github.com/OCA/manufacture/commit/1288b62c94386201be00cae0edec60abcdf5107d) ?

I use `Rebase children of xxx interactively` with SourceTree to squash but don't squash all. See : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 :

`Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot. IMPORTANT: Don't squash legit translation commits, authored by their translators, with the message "Translated using Weblate (...)".`

**Comment by pedrobaeza** [comment]
Look at this squashing guide: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by bosd — APPROVED** [review]

**Comment by dalonsod** [comment]
> I need some help on squashing. Can somebody guide me on how to squash the commits from [19b549b](https://github.com/OCA/manufacture/commit/19b549ba455f3bd85ba4981674abbdd7c17feb35) to [1288b62](https://github.com/OCA/manufacture/commit/1288b62c94386201be00cae0edec60abcdf5107d) ?

Hello @janikvonrotz why do you want to make such squash? There are a lot of changes there, history would be lost, and commit authorship as well.

**Pull request merged**
