### PR TITLE
[14.0][MIG] quality_control_team_oca: Migration to 14.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @WesleyOliveira98 @Alisson-Jns 

Changes in v14.0:

1. Added aria-label, role, and title attributes to the `<i>` tag. Omitting these attributes resulted in the mentioned warning.
2. Replaced the deprecated method `_company_default_get("qc.team")` with `self.env.company`.

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by wsnipez — APPROVED** [review]
LGTM

**Review by WesleyOliveira98 — APPROVED** [review]
LGTM

**Comment by kaynnan** [comment]
ping @OCA/manufacturing-maintainers

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
