### PR TITLE
[14.0][MIG] product_mrp_info

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration 

CC  @ForgeFlow

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM

**Comment by lk-eska** [comment]
This feature is included in standard MRP module, isn't it?

**Comment by HviorForgeFlow** [comment]
> This feature is included in standard MRP module, isn't it?

Feature is slightly different. While in Odoo core you can see a report (pivot, graph view) about how many products have been manufactured, this modules add another smart button that list all MO's involving that product.

FYG @lk-eska

**Comment by andreampiovesana** [comment]
merge?

**Review by andreampiovesana — COMMENTED** [review]
go

**Comment by ypapouin** [comment]
@sbidoul, do you know why this build (`ba4e8df72-91e9-4e12-9515-c3682f203899`) is not found on runboat ?

**Comment by sbidoul** [comment]
@ypapouin it's an old one. It has likely been removed to make room for newer ones.

A rebase of the PR should trigger a new build.

**Comment by ypapouin** [comment]
@sbidoul, Ok I was not aware about this behavior.

@HviorForgeFlow, can you rebase this PR to make a functional review ? also I think that there are some commits that should be squashed according to https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Review by ypapouin — APPROVED** [review]
LGTM - Code/Functional Review

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Pull request merged**
