### PR TITLE
[13.0][MIG] base_repair: Migration to 13.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @rvalyi @eduaparicio

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by rvalyi — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @dreispt

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by dreispt — APPROVED** [review]

**Pull request merged**
