### PR TITLE
[12.0][FIX] repair_refurbish : Issue with stock location movement

### PR DESCRIPTION
**Pull request by bodedra**
Issue Reference : #367

### CODE REVIEW

**Comment by bodedra** [comment]
@jbeficent @lreficent @grindtildeath @pedrobaeza

**Comment by bodedra** [comment]
@aheficent

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by grindtildeath — COMMENTED** [review]
I don't really see what is different after this change, maybe can you add a test to explicit the issue ?

**Comment by bodedra** [comment]
@grindtildeath Thanks for your review. Here is full scenario #367 and help us to improve behaviour in 12.0. It works fine 11.0

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
For me the code diff look exactly equivalent. I also think that a unit test would help to highlight the error.

**Pull request closed without merging**
