### PR TITLE
 [13.0][MIG] quality_control_team_oca: Migration to 13.0

### PR DESCRIPTION
**Pull request by kaynnan**
Migration and rename quality_control_team to quality_control_team_oca

cc @marcelsavegnago @WesleyOliveira98

### CODE REVIEW

**Review by augustodinizl — APPROVED** [review]
LGTM - Functional review - OK!

image

**Review by marcelsavegnago — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by kaynnan** [comment]
This last forced commit made was related to an adjustment in the  element to correctly render the image.

image

**Comment by kaynnan** [comment]
This last force-pushed made was related to an adjustment in the  element to correctly render the image.

image

**Comment by kaynnan** [comment]
ping @OCA/manufacturing-maintainers

**Pull request merged**
