### PR TITLE
Add french translations for mrp_bom_product_details

### PR DESCRIPTION
**Pull request by arthru**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Files are technically correct, so :+1:, but I cannot say about the translation.

**Comment by anajuaristi** [comment]
:+1: 

Single doubt.

Why Bill of materials is translated as Nomenclature and not like "liste des matériaux"?

**Comment by max3903** [comment]
@anajuaristi This is the right term to use in the current context and also the one used in the official module:
https://github.com/odoo/odoo/blob/8.0/addons/mrp/i18n/fr.po#L369

**Comment by max3903** [comment]
:+1:

**Pull request merged**
