### PR TITLE
mrp_bom_reference_selection

### PR DESCRIPTION
**Pull request by AbdulrhmanGad**
Abdulrhman Mohammed Abdeldaiem 
a.abdeldaiem@dvit.me

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@AbdulrhmanGad  Can you explain the purpose of this PR?

**Comment by LoisRForgeFlow** [comment]
@AbdulrhmanGad I'm still not getting the point of this. Let me know what you are trying to do and I may be able to help you.

**Comment by AbdulrhmanGad** [comment]
I am trying to upload 3 modules in one time, but someone told me must upload one by one

**Comment by LoisRForgeFlow** [comment]
Yes, one module per PR is the rule to ease reviews. 

I see that these are migrations, please have a look to the wiki for the procedure to migrate: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by LoisRForgeFlow** [comment]
No answer for a long time, I am closing this, please reopen if you still think it is relevant.

**Pull request closed without merging**
