### PR TITLE
[MIG] mrp_production_grouped_by_product: Migration to 15.0

### PR DESCRIPTION
**Pull request by punt-sistemes-salva**
Migration of the module: mrp_production_grouped_by_product

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by punt-sistemes-salva** [comment]
Done.

¿How can we add the module to the list of modules to migrate? I can't find it in documentation.

Thanks

**Comment by punt-sistemes-salva** [comment]
Buenas @pedrobaeza, estan todos los test ok se podria mergear?

Saludos y gracias

**Comment by pedrobaeza** [comment]
This requires the review of at least two persons, and one of them being PSC of the repository.

**Comment by pedroortega-punt** [comment]
@pedrobaeza Reviewed and working on a client

**Comment by pedrobaeza** [comment]
Please do the proper GitHub review mechanism on the "Files changed" tab.

**Review by pedroortega-punt — APPROVED** [review]
Reviewed and working on a client

**Comment by pedroortega-punt** [comment]
@LoisRForgeFlow Good morning, you can take a look and check to see if it can be merged

**Review by LoisRForgeFlow — APPROVED** [review]
Code review + functional review :+1: 

/ocabot merge nobump

**Comment by punt-sistemes-salva** [comment]
@LoisRForgeFlow @vipvalen  Thanks a lot!

**Pull request merged**
