### PR TITLE
ADD Group by project_id in mrp.productions

### PR DESCRIPTION
**Pull request by jcarlosmontoya**
ADD Group by project_id in mrp.productions tree view

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code review - it isn't the best option to use string in xpath expression but odoo didn't give you many options... so I think is fine in v8 :+1:

**Comment by rubencabrera** [comment]
Works as expected, surprising it wasn't there before.

**Comment by damendieta** [comment]
It will fail in v9, maybe it's better to think in migrations and use 

`<group position="inside">`
or
`//group/filter[2]`

 instead.

**Review by bodedra — APPROVED** [review]

**Pull request merged**
