### PR TITLE
[14.0][IMP] mrp_subcontracting_purchase_link: direct link of subcontracting transfers in PO

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Add button in PO to navigate directly to the subcontracting production transfers

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM! The only thing that bothers me a little is that both are called Productions. Anyway, I don't know what short word would be good.

**Review by AaronHForgeFlow — APPROVED** [review]
Code LG

**Comment by JordiMForgeFlow** [comment]
Closing this improvement as there is already a module available: https://github.com/OCA/manufacture/blob/14.0/mrp_subcontracting_resupply_link

**Pull request closed without merging**
