### PR TITLE
[FIX] mrp_operations_extension: Don't check option "Calc Cycles by Bo…

### PR DESCRIPTION
**Pull request by Daniel-CA**
Don't check option "Calc Cycles by BoM Quantity" even if not desired.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The option is correct. What you need to do is to put to False the parameter.

**Comment by Daniel-CA** [comment]
Hi @pedrobaeza, the problem comes when you update the module or due to an update=all, it always checks it again, even if you have marked to False.

**Comment by pedrobaeza** [comment]
No, the noupdate="1" prevents that. The only problem is that you remove the record, then that attribute makes that to recreate it. But it's put on purpose for always seeing the value (False or True). Try again.

**Comment by Daniel-CA** [comment]
Hi @pedrobaeza,
You are right, but when I try to update the attribute value I get an integrity error because the record is already accessed, don't know why it leaves unlinking it but not updating.
```
    if rec:
            if not value:      
                rec.unlink()
            else:
                rec.value = value
```
My change:
```
    if rec:
        rec.value = value
```
Any suggestions?

**Comment by pedrobaeza** [comment]
I don't get you. What is the relation between the PR and your code?

**Comment by Daniel-CA** [comment]
The PR is a "fix" for the problem I was talking, when the mark is uncheked the param key is erased, so if the module is updated the key is recreated again with the True value even if it is in a noupdate section.

**Comment by pedrobaeza** [comment]
But where is that code? The problem is in your code, not here.

**Comment by Daniel-CA** [comment]
That code is in the `res_config.py` file.

**Comment by pedrobaeza** [comment]
OK, the error is there then. You have to put:
```
    def _write_or_create_param(self, key, value):
        param_obj = self.env['ir.config_parameter']
        rec = self._get_parameter(key)
        if rec:
            rec.value = str(value)
        else:
            param_obj.create({'key': key, 'value': str(value)})
```

**Comment by Daniel-CA** [comment]
That's the change that I was talking about in my previous message.

**Comment by pedrobaeza** [comment]
OK, we have agreement then!

**Comment by Daniel-CA** [comment]
And do you have any suggestions to avoid the integrity error?

**Comment by pedrobaeza** [comment]
With the new code do you still have that problem?

**Comment by Daniel-CA** [comment]
Yes, and don't know why.

**Comment by Daniel-CA** [comment]
Changes done! Thanks @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by elicoidal — APPROVED** [review]

**Review by agaldona — APPROVED** [review]
:+1:

**Pull request merged**
