### PR TITLE
[15.0][MIG] mrp_multi_level

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@ChrisOForgeFlow could you include this recent merge for v14 here https://github.com/OCA/manufacture/pull/701?

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow could you include this recent merge for v14 here #701?

Done

**Comment by LoisRForgeFlow** [comment]
Rebased and fixed pre-commit

**Review by LoisRForgeFlow — APPROVED** [review]
Functional and technical review :+1:

**Pull request merged**
