### PR TITLE
[12.0][MIG/REN] mrp_repair_discount -> repair_discount

### PR DESCRIPTION
**Pull request by mariaasunciondaza**
@guadaltech
@NachoAlesLopez

### CODE REVIEW

**Review by NachoAlesLopez — APPROVED** [review]
Functional and code review: LGTM!

**Comment by elvise** [comment]
Hi, any good news for merge...?
If I can help please let me know...

**Review by ps-tubtim — APPROVED** [review]
Functional Test: ok.

**Comment by LoisRForgeFlow** [comment]
@mariaasunciondaza Please squash transifex commits together and we'll be ready to merge.

**Comment by LoisRForgeFlow** [comment]
Thanks!

/ocabot merge

**Pull request merged**
