### PR TITLE
[16.0][MIG] mrp_subcontracting_no_negative: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
@qrtl

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
Closed this PR because this module is not required and stock_no_negative will block the no_negative for component products.

**Comment by jans23** [comment]
I found this module useful in 15.0 and I couldn't find an alternative in Odoo 18.0. I see you closed your PR so I'm wondering what was your motivation and perhaps you know an alternative?

**Comment by AungKoKoLin1997** [comment]
> I found this module useful in 15.0 and I couldn't find an alternative in Odoo 18.0. I see you closed your PR so I'm wondering what was your motivation and perhaps you know an alternative?

@jans23 If I remember the history of this module correctly, this module is created because `stock_no_negative` is blocked the operation for finished product of subcontracting order in v15.
So, I made some adjustments to [stock_no_negative](https://github.com/OCA/stock-logistics-workflow/tree/16.0/stock_no_negative) and created [mrp_subcontracting_skip_no_negative](https://github.com/OCA/manufacture/tree/16.0/mrp_subcontracting_skip_no_negative) to cover that.
So, `mrp_subcontracting_no_negative` is not needed anymore because of that changes and we can just use `stock_no_negative` along with `mrp_subcontracting_skip_no_negative`.

Btw, `mrp_subcontracting_skip_no_negative` is still in open PR for odoo 18. It would be good if you review.
https://github.com/OCA/manufacture/pull/1674

**Comment by jans23** [comment]
Thank you for the explanation. Very helpful.

@hitesh-erpharbor could you test and review #1674 please?

**Pull request closed without merging**
