### PR TITLE
[14.0][IMP] mrp_bom_component_menu: import, create, delete, edit MRP BOM lines

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

This change is to allow import and creation of BOM lines independently

**Review by geomer198 — APPROVED** [review]

**Comment by geomer198** [comment]
Code review ok!

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers postive about this improvement?

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers shall we merge?

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers good for merging?

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers what do you say?

**Comment by francesco-ooops** [comment]
@pedrobaeza would this be ok?

**Comment by pedrobaeza** [comment]
Why don't you become maintainers of the module and thus you don't need to ask for the merge of this IMP/FIX?

/ocabot merge minor

**Comment by francesco-ooops** [comment]
> Why don't you become maintainers of the module and thus you don't need to ask for the merge of this IMP/FIX?
> 
> /ocabot merge minor

that could be a good idea! 

if we come across this situation, do you suggest to make 2 PRs? one for becoming maintainers and one for the IMP?

**Comment by pedrobaeza** [comment]
You can do it in the same PR with 2 separate commits, and also on migrations.

**Pull request merged**
