### PR TITLE
[13.0][MIG] repair timeline: Migration to 13.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**
cc @rvalyi @pedrobaeza 

Depends https://github.com/OCA/manufacture/pull/600 (merged)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by marcelsavegnago** [comment]
> Please check Travis

Hello @pedrobaeza . This PR depends of #600

**Comment by marcelsavegnago** [comment]
@pedrobaeza PR is OK now

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by rvalyi — CHANGES_REQUESTED** [review]
I get this error when trying to click on the timeline view in the Runbot:

**Comment by marcelsavegnago** [comment]
@rvalyi Thanks. I will check now.

**Comment by marcelsavegnago** [comment]
@rvalyi fixed up. I'm already correcting in version 12.0.

**Comment by marcelsavegnago** [comment]
Everything green

**Comment by Reyes4711-S73** [comment]
Functional review

**Review by Reyes4711-S73 — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Comment by marcelsavegnago** [comment]
ping @pedrobaeza

**Comment by marcelsavegnago** [comment]
ping @bodedra

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Comment by bodedra** [comment]
@marcelsavegnago I have added one patch. Would you please review it?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago I have added one patch. Would you please review it?

@bodedra Merged.. Thanks

**Comment by bodedra** [comment]
@marcelsavegnago I will green this PR later today. My target to add `timeline` view only instead of override all views. Otherwise if someone has used same action XML ID to override views, we can lose this timeline view.

**Comment by bodedra** [comment]
@marcelsavegnago I apologize for interfere in this PR and crash it. I have opened new PR at https://github.com/OCA/manufacture/pull/636. We can close this PR if you agree.

JFI, I have removed my all changes.

@Reyes4711 are you available for review PR(https://github.com/OCA/manufacture/pull/636)?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago I apologize for interfere in this PR and crash it. I have opened new PR at #636. We can close this PR if you agree.
> 
> JFI, I have removed my all changes.
> 
> @Reyes4711 are you available for review PR(#636)?

@bodedra Your help is most welcome. 🍻

**Pull request closed without merging**
