### PR TITLE
[11.0] [ADD] new module quality_control_plan

### PR DESCRIPTION
**Pull request by mymage**
Rif. #425

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
I have checked, works well for me

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
Are you planning to add any unit test? codecov is quite low.

**Comment by mymage** [comment]
> 
> 
> Are you planning to add any unit test? codecov is quite low.

@LoisRForgeFlow Unfortunately I don't know how to set up unit test. I know it is serious lack.
I will try to ask help to friends, but if you have time to do a suggestion I will appreciate.

**Comment by mymage** [comment]
@LoisRForgeFlow I start to do some test, but because it is my first time at the moment I'm halted at the first complication.
In the test_plan.py I inserted some _todo_ steps that I think will be a god test to do: have you a suggestion for "create a picking"?
UPDATE: I did a little step using only the inspection. I'm confident to complete all the cases.

**Comment by mymage** [comment]
@LoisRForgeFlow @dreispt I completed the module with tests. This is my first time so if you give it a comment I will appreciate.
For the rest I think it is ok.

**Pull request merged**
