### PR TITLE
[12.0][ADD] repair_timeline

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Add repair timeline view

Depends #594

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not call it simply `repair_timeline` (analog to `project_timeline` for example)?

**Comment by marcelsavegnago** [comment]
> Why not call it simply `repair_timeline` (analog to `project_timeline` for example)?

@pedrobaeza Done

**Comment by marcelsavegnago** [comment]
ping @pedrobaeza @rvalyi @eduaparicio

**Review by pedrobaeza — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
