### PR TITLE
[MIG] mrp_bom_product_detail : Migration to 10.0

### PR DESCRIPTION
**Pull request by bimajatiwijaya**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
which repository did you get the module from? I cannot find it here at OCA/manufacture but I see in the README that many people have contributed to it.

**Comment by bimajatiwijaya** [comment]
On previous merge request i did mistake on message mrp_product_details it should be mrp_bom_product_details.

**Comment by LoisRForgeFlow** [comment]
@bimajatiwijaya I see, thanks. Please, follow the the migration method described here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

This needs to be done in order to preserve commit history of the module.

**Comment by StefanRijnhart** [comment]
Hi @bimajatiwijaya, we have not heard back from you in some time. Do you need help with the proper migration using git-format-patch?

**Comment by bimajatiwijaya** [comment]
@StefanRijnhart : yes i need help.

**Comment by StefanRijnhart** [comment]
So where do you get stuck when you follow the procedure from https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch?

**Comment by LoisRForgeFlow** [comment]
No answer from the author for a long time, closing. Please reopen if still relevant.

**Pull request closed without merging**
