### PR TITLE
[16.0][MIG] repair_calendar_view

### PR DESCRIPTION
**Pull request by unaiberis**

### CODE REVIEW

**Review by anajuaristi — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I have aborted it, as checking twice, this should go to OCA/repair.

**Comment by anajuaristi** [comment]
@pedrobaeza thank you for review. We will propose PR to OCA/repair

**Pull request closed without merging**
