### PR TITLE
[MIG] Make mrp_production_partner_note installable in v9

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include tests for not dropping coverage.

**Comment by oihane** [comment]
@pedrobaeza could you please review, coverage is now 100%

**Comment by pedrobaeza** [comment]
Thank you!

:+1:

**Comment by max3903** [comment]
@oihane You have 2 warnings in Travis:

```
Start lint check just in modules changed
************* Module mrp_production_partner_note.__openerp__
mrp_production_partner_note/__openerp__.py:5: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
mrp_production_partner_note/__openerp__.py:5: [C8102(manifest-required-key), ] Missing required key "images" in manifest file
```

**Comment by oihane** [comment]
@max3903 I'll add the `license` one, but is it really required the `images` one?

**Comment by max3903** [comment]
@oihane It's a warning, not a fail, but in those days, nobody reads and some people are also more visual than textual. So I can only encourage to provide screenshots... :)

**Comment by oihane** [comment]
@max3903 added license and images (screenshot of partner in edit mode to show notes field)

**Comment by oihane** [comment]
@max3903 @pedrobaeza the PR is green now

**Comment by max3903** [comment]
:+1:

**Pull request merged**
