### PR TITLE
[10.0] Migrate mrp_sale_info

### PR DESCRIPTION
**Pull request by bimajatiwijaya**
- Change workcenter.line to mrp.workorder
- move_prod_id not exist. search sale information from move_finished_ids and changed related field to compute field
- add unit test

### CODE REVIEW

**Comment by mamcode** [comment]
Hi @bimajatiwijaya, I have added changes to this pull request locally, are the same changes proposed in the pr #93 but for version 10.0. Except that i don't add the field sale_line because I don't see useful as already the MO/WO has relation with sale.order through field sale_id.

Do you think it's convenient to add my commit to this pr or should I create a new pull request based on this pr (is this possible?)? 

@pedrobaeza

**Comment by pedrobaeza** [comment]
You can make a PR over the original Bima's branch.

**Comment by mamcode** [comment]
Thanks @pedrobaeza I will do that :+1:

**Comment by mamcode** [comment]
@bimajatiwijaya @pedrobaeza PR done https://github.com/bimajatiwijaya/manufacture/pull/1

**Comment by humanytek** [comment]
@bimajatiwijaya Fields sale_id and partner_id must be stored because the filters (group by) do not work ... the fields to be grouped must be fields stored in the database, it does not work with computed or related fields o/

**Comment by mamcode** [comment]
@bimajatiwijaya Fields sale_id and partner_id must be stored because the filters (group by) do not work ... the fields to be grouped must be fields stored in the database, it does not work with computed or related fields o/

**Comment by bimajatiwijaya** [comment]
Hi @mamcode ,
Before both field are computed field. 
If using stored sale_id and partner_id will empty. Unit test always failed.
So i changed way to get sale info. Now all field are not computed but stored value.
I extend make_mo to fulfill sale information.

**Comment by mamcode** [comment]
Now I understand @bimajatiwijaya :-) Good!

**Review by congdpt — APPROVED** [review]

**Comment by bimajatiwijaya** [comment]
Up :)

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
