### PR TITLE
[13.0][FIX] remove user_id (duplicate)

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This field was in the repair module in version 13.

V13
https://github.com/odoo/odoo/blob/d58844841fcc13adb948c07fc9af3c73c767c287/addons/repair/models/repair.py#L108

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/manufacturing-maintainers

**Review by mileo — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @rvalyi

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by HaraldPanten — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
> /ocabot merge minor

I don't think the command was executed.

**Pull request merged**
