### PR TITLE
[12.0][IMP] quality_control: add chatter to quality tests

### PR DESCRIPTION
**Pull request by cubells**

### CODE REVIEW

**Review by antonio-trey — APPROVED** [review]
👌🏻

**Comment by pedrobaeza** [comment]
Shouldn't this be part of the main module?

**Comment by cubells** [comment]
@pedrobaeza Yes. If you want, I can add this code to `quality_control`, no problem.

**Comment by pedrobaeza** [comment]
Yeah, I think so.

**Comment by cubells** [comment]
@pedrobaeza done!

**Comment by pedrobaeza** [comment]
Change commit message and PR title

**Comment by cubells** [comment]
@pedrobaeza sorry, done!

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port it to upper branches:

/ocabot merge minor

**Pull request merged**
