### PR TITLE
[12.0][IMP] Add repair duration field in repair_calendar_view (like maintenance)

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Add repair duration field (functionality similar to the maintenance module)

### CODE REVIEW

**Review by jpcarassato — APPROVED** [review]
Ok!

**Review by eduaparicio — APPROVED** [review]
Code review looks ok! Approved.

**Comment by marcelsavegnago** [comment]
@OCA/manufacturing-maintainers is it possible to merge this PR?

**Comment by LoisRForgeFlow** [comment]
@marcelsavegnago Hi, travis is red, can you check it?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago Hi, travis is red, can you check it?

@LoisRForgeFlow Can you help me? The error appears to be occurring when testing the mrp_subcontracting module.

**Comment by yostashiro** [comment]
@marcelsavegnago I suppose this PR https://github.com/OCA/manufacture/pull/527 fixes the issue with the test in mrp_subcontracting.

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago I suppose this PR #527 fixes the issue with the test in mrp_subcontracting.

@yostashiro Thanks for the tip .. the PR was merged and now the error do travis is resolved.

**Comment by marcelsavegnago** [comment]
@LoisRForgeFlow travis errors fix. Can you review please?

**Review by rvalyi — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@OCA/manufacturing-maintainers is it possible to merge this PR?

**Comment by marcelsavegnago** [comment]
@LoisRForgeFlow is it possible to merge this PR? please :)

**Comment by marcelsavegnago** [comment]
@pedrobaeza Can you help me with the merge of this PR?

**Comment by pedrobaeza** [comment]
Not sure why it's failing. Can you rebase to see if the error arises here as well?

**Comment by pedrobaeza** [comment]
Opened issue at #550

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
