### PR TITLE
[13.0][IMP] mrp_multi_level

### PR DESCRIPTION
**Pull request by NuriaXifre**
Two little changes to optimize the low_level_code_calculation method. ~ @ForgeFlow @JordiBForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Code review

**Review by bodedra — APPROVED** [review]

**Review by LoisRForgeFlow — COMMENTED** [review]
@NuriaMForgeFlow Could you run pre-commit on your commit and take the ocassion to add a little descripton to the commit msg?

**Comment by HviorForgeFlow** [comment]
:top:

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
