### PR TITLE
[15.0][MIG] mrp_warehouse_calendar

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration v.15.0
@BernatPForgeFlow
@AaronHForgeFlow
@MariaDForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
Functional review. LGTM.

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test, working smoothly

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
