### PR TITLE
[13.0][FIX] mrp_production_request: correct handling of serveral procurements

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Fixes https://github.com/OCA/manufacture/issues/529. Supersedes https://github.com/OCA/manufacture/pull/532.

cc @guimarc-br

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by guimarc-br** [comment]
@LoisRForgeFlow Thank, and I  Totally agree with this solution. Could we merge it ?

**Comment by LoisRForgeFlow** [comment]
@guimarc-br yes, could you give your approval via review?

**Comment by guimarc-br** [comment]
Sure I approve , I just cannot put my name as approver

**Comment by LoisRForgeFlow** [comment]
@guimarc-br You can do it by navigating to "files changed":

image

**Review by guimarc-br — APPROVED** [review]

**Comment by guimarc-br** [comment]
Done

**Comment by LoisRForgeFlow** [comment]
@guimarc-br Thanks, and sorry for the delay on this topic.

/ocabot merge patch

**Pull request merged**
