### PR TITLE
[12.0][FIX] mrp_subcontracting: Skip processed MO when validating receipt

### LINKED ISSUE #560: [12.0] mrp_subcontracting: Receipt cannot be validate if MO is processed first
Steps to reproduce:
1. Create a subcontract BoM with material that is tracked by lot, e.g. Test1 is tracked by lot.
image
image
2. Create a PO with the product and confirm the order.
3. Process the MO first (state: done).
4. Validate The receipt of the PO.

Current behavior:
Odoo Server Error is raised and the picking cannot be validated.
image

### PR DESCRIPTION
**Pull request by TimLai125**
Check state of the MO before trying to process it, skip processed MO when validating receipt.
Fixes: #560

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This code is from odoo, so maybe Odoo v13 is affected as well by this?

**Review by pedrobaeza — APPROVED** [review]

**Comment by TimLai125** [comment]
@pedrobaeza Yes, I just noticed https://github.com/odoo/odoo/issues/61927 but I think Odoo has not backport the fix from 14.0 to 13.0.

**Review by yostashiro — APPROVED** [review]
LGTM 👍

**Pull request merged**
