### PR TITLE
[15.0] [FIX] `mrp_bom_attribute_match`: structure and cost report

### PR DESCRIPTION
**Pull request by ivantodorovich**
This PR fixes two issues with this module:

1. An issue with `mrp_account`'s button ["Compute Price from Bom"](https://github.com/odoo/odoo/blob/c087979c853bfcba28094d784d665033c42a1ccc/addons/mrp_account/views/product_views.xml#L13)
2. An issue with the [Structure and Cost](https://github.com/odoo/odoo/blob/c087979c853bfcba28094d784d665033c42a1ccc/addons/mrp/views/mrp_bom_views.xml#L47) smart button

In both cases, when called on a bom that has a component template and no `product_id` set, a very similar traceback was raised:

```python-traceback
  File "/odoo/src/addons/mrp_account/models/product.py", line 95, in _compute_bom_price
    total += line.product_id.uom_id._compute_price(line.product_id.standard_price, line.product_uom_id) * line.product_qty
  File "/odoo/src/addons/uom/models/uom_uom.py", line 234, in _compute_price
    self.ensure_one()
  File "/odoo/src/odoo/models.py", line 5207, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ExceptionThe above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: uom.uom()
```

NOTE: It's easier to review commit by commit

### CODE REVIEW

**Review by yankinmax — APPROVED** [review]
Not familiar with the module: code seems ok.

**Review by jcoux — APPROVED** [review]
Technically seems good :+1:

**Review by ilyasProgrammer — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/manufacturing-maintainers could this be merged? :)

**Comment by francesco-ooops** [comment]
@pedrobaeza what do you think?

**Comment by pedrobaeza** [comment]
Please squash a bit the commit history.

**Comment by ivantodorovich** [comment]
Hello @pedrobaeza !

As it is right now, each commit is  atomic, taking care of a specific concern.
Squashing would make the history dificult to read.

**Comment by pedrobaeza** [comment]
OK, as I haven't followed the thread, just do the administrative task given the reviews:

/ocabot merge minor

**Comment by ivantodorovich** [comment]
Thanks 🙏🏻 !!

**Comment by francesco-ooops** [comment]
@ivantodorovich seems mrp_account_bom_attribute_match has corrupt readme, could you fix?

**Comment by ivantodorovich** [comment]
Oops,. thanks for noticing @francesco-ooops !
Fixed here: https://github.com/OCA/manufacture/pull/983

**Pull request merged**
