### PR TITLE
10.0 mig quality control mrp

### PR DESCRIPTION
**Pull request by SimoRubi**
Migration of quality_control_mrp, depends on https://github.com/OCA/manufacture/pull/282

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase this

**Comment by SimoRubi** [comment]
Rebased after #282

**Comment by SimoRubi** [comment]
fixing runbot with https://github.com/OCA/manufacture/pull/288

**Review by mrcast — APPROVED** [review]
Functional test OK

**Review by anajuaristi — APPROVED** [review]
:+1: 
Go go go :)

Thank you very much!!

**Comment by SimoRubi** [comment]
Thanks for the review @anajuaristi

**Comment by SimoRubi** [comment]
@OCA/manufacturing-maintainers could you please review?
Thanks

**Comment by pedrobaeza** [comment]
Please squash a bit the commit history by author/logic set (including your fixups).

**Review by pedrobaeza — APPROVED** [review]

**Comment by SimoRubi** [comment]
@pedrobaeza thanks for the review; squashed all the things by author and fixed up my commits, I also fixed the email address in https://github.com/OCA/manufacture/pull/283/commits/d46c9aa5513082d30e81716db8f39af771146da5.

**Pull request merged**
